<?php
/**
 * The set of HTTP entry points is pinned, and so is the way each one is gated.
 *
 * Every file that a browser can request directly is part of the attack surface
 * the security audit walked. A script appearing under the root or under
 * `admin/` without being added here has not been audited, so it fails the
 * build; the same goes for a second script skipping the global CSRF gate or
 * loading without `include/common.php`.
 *
 * @copyright (C) 2008-2012 PunBB, partially based on code (C) 2008-2009 FluxBB.org
 * @license http://www.gnu.org/licenses/gpl.html GPL version 2 or higher
 * @package PunBB
 */

use PHPUnit\Framework\TestCase;

class EntryPointInventoryTest extends TestCase {
	/** Generated by the installer, absent from a bare checkout, never requested directly. */
	private const UNTRACKED = array('config.php');

	/** @var list<string> */
	private const ROOT_SCRIPTS = array(
		'delete.php', 'edit.php', 'extern.php', 'footer.php', 'header.php',
		'help.php', 'index.php', 'login.php', 'misc.php', 'moderate.php',
		'post.php', 'profile.php', 'register.php', 'rewrite.php', 'search.php',
		'userlist.php', 'viewforum.php', 'viewtopic.php',
	);

	/** @var list<string> */
	private const ADMIN_SCRIPTS = array(
		'bans.php', 'categories.php', 'censoring.php', 'db_update.php',
		'extensions.php', 'forums.php', 'groups.php', 'index.php',
		'install.php', 'prune.php', 'ranks.php', 'reindex.php', 'reports.php',
		'settings.php', 'users.php',
	);

	/**
	 * `include/common.php` rejects any POST without a valid `csrf_token`. Only
	 * post.php opts out, and it checks the token itself for every poster.
	 *
	 * @var list<string>
	 */
	private const SKIPS_GLOBAL_CSRF_GATE = array('post.php');

	/**
	 * Scripts that never reach the CSRF gate because they never load
	 * `include/common.php`: two are includes guarded by `defined('FORUM')`,
	 * one is the URL rewriter, and the installer and the updater run before a
	 * usable configuration exists.
	 *
	 * @var list<string>
	 */
	private const WITHOUT_COMMON = array(
		'admin/db_update.php', 'admin/install.php', 'footer.php', 'header.php',
		'rewrite.php',
	);

	public function testTheRootScriptsOnDiskAreTheAuditedOnes(): void {
		$this->assertSame(self::ROOT_SCRIPTS, $this->scripts(''));
	}

	public function testTheAdminScriptsOnDiskAreTheAuditedOnes(): void {
		$this->assertSame(self::ADMIN_SCRIPTS, $this->scripts('admin/'));
	}

	public function testOnlyPostPhpSkipsTheGlobalCsrfGate(): void {
		$this->assertSame(
			self::SKIPS_GLOBAL_CSRF_GATE,
			$this->matching('#define\(\'FORUM_SKIP_CSRF_CONFIRM\'#')
		);
	}

	public function testTheGlobalCsrfGateStillRejectsUntokenedPosts(): void {
		$gate = <<<'GATE'
if (!empty($_POST) && (isset($_POST['confirm_cancel']) || !csrf_token_matches($_POST['csrf_token'] ?? null, get_current_url())) && !defined('FORUM_SKIP_CSRF_CONFIRM'))
	csrf_confirm_form();
GATE;

		$this->assertStringContainsString($gate, file_get_contents(FORUM_ROOT.'include/common.php'));
	}

	public function testOnlyTheInstallersAndIncludesLoadWithoutCommonPhp(): void {
		$all = array_merge(
			$this->scripts(''),
			array_map(static fn (string $script): string => 'admin/'.$script, $this->scripts('admin/'))
		);

		$without = array_values(array_diff($all, $this->matching('#include/common\.php#')));
		sort($without);

		$this->assertSame(self::WITHOUT_COMMON, $without);
	}

	/**
	 * The directly requestable PHP files in $dir, sorted.
	 *
	 * @return list<string>
	 */
	private function scripts(string $dir): array {
		$found = array();

		foreach (glob(FORUM_ROOT.$dir.'*.php') as $path) {
			$name = basename($path);
			if (!in_array($name, self::UNTRACKED, true))
				$found[] = $name;
		}

		sort($found);

		return $found;
	}

	/**
	 * The entry points whose source matches $pattern, root first, sorted.
	 *
	 * @return list<string>
	 */
	private function matching(string $pattern): array {
		$found = array();

		foreach (self::ROOT_SCRIPTS as $script)
			if (preg_match($pattern, file_get_contents(FORUM_ROOT.$script)))
				$found[] = $script;

		foreach (self::ADMIN_SCRIPTS as $script)
			if (preg_match($pattern, file_get_contents(FORUM_ROOT.'admin/'.$script)))
				$found[] = 'admin/'.$script;

		sort($found);

		return $found;
	}
}
