<?php /* The form moving the users selected into another group. Every variable is escaped unless it is Html. */ ?>
	<div class="main-subhead">
		<h2 class="hn"><span><?= $aus['Change group head'] ?></span></h2>
	</div>
	<div class="main-content main-frm">
		<form class="frm-form" method="post" accept-charset="utf-8" action="<?= $action ?>">
			<div class="hidden">
				<input type="hidden" name="csrf_token" value="<?= $token ?>" />
				<input type="hidden" name="users" value="<?= $users ?>" />
			</div>
			<fieldset class="frm-group group<?= $numbers['group'] ?>">
				<legend class="group-legend"><span><?= $aus['Move users legend'] ?></span></legend>
				<div class="sf-set set<?= $numbers['item'] ?>">
					<div class="sf-box select">
						<label for="fld<?= $numbers['field'] ?>"><span><?= $aus['Move users to label'] ?></span></label><br />
						<span class="fld-input"><select id="fld<?= $numbers['field'] ?>" name="move_to_group">
<?php foreach ($groups as $group): ?>
								<option value="<?= $group['id'] ?>"<?php if ($group['default']): ?> selected="selected"<?php endif ?>><?= $group['title'] ?></option>
<?php endforeach ?>
						</select></span>
					</div>
				</div>
			</fieldset>
			<div class="frm-buttons">
				<span class="submit primary"><input type="submit" name="change_group_comply" value="<?= $aus['Change group'] ?>" /></span>
				<span class="cancel"><input type="submit" name="change_group_cancel" value="<?= $common['Cancel'] ?>" /></span>
			</div>
		</form>
	</div>
