<?php /* The form merging topics into the oldest of them, and whether redirects are left. Every variable is escaped unless it is Html. */ ?>
	<div class="main-head">
		<h2 class="hn"><span><?= $misc['Confirm topic merge'] ?></span></h2>
	</div>
	<div class="main-content main-frm">
		<form class="frm-form" method="post" accept-charset="utf-8" action="<?= $action ?>">
			<div class="hidden">
				<?= $hiddenFields, "\n" ?>
			</div>
<?= $positions['pre_fieldset'] ?>
			<fieldset class="frm-group group<?= $numbers['group'] ?>">
				<legend class="group-legend"><strong><?= $misc['Merge topics'] ?></strong></legend>
<?= $positions['pre_redirect_checkbox'] ?>
				<div class="sf-set set<?= $numbers['redirect_item'] ?>">
					<div class="sf-box checkbox">
						<span class="fld-input"><input type="checkbox" id="fld<?= $numbers['redirect_field'] ?>" name="with_redirect" value="1" /></span>
						<label for="fld<?= $numbers['redirect_field'] ?>"><?= $misc['Leave merge redirects'] ?></label>
					</div>
				</div>
<?= $positions['pre_fieldset_end'] ?>
			</fieldset>
<?= $positions['fieldset_end'] ?>
			<div class="frm-buttons">
				<span class="submit primary"><input type="submit" name="merge_topics_comply" value="<?= $misc['Merge'] ?>" /></span>
				<span class="cancel"><input type="submit" name="cancel" value="<?= $common['Cancel'] ?>" formnovalidate /></span>
			</div>
		</form>
	</div>
