<?php /* The administration's chrome. Every variable is escaped unless it is Html. */ ?>
<!DOCTYPE html>
<html <?= $local ?>>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?= $head, "\n" ?>
</head>
<body>
<?= $messages, "\n" ?>
<div id="brd-wrap" class="brd">
<div <?= $page ?>>

<div id="brd-head" class="gen-content">
	<?= $skip, "\n" ?>
	<?= $title, "\n" ?>
	<?= $desc, "\n" ?>
</div>

<div id="brd-navlinks" class="gen-content">
	<?= $navlinks, "\n" ?>
	<?= $admod, "\n" ?>
</div>

<div id="brd-visit" class="gen-content">
	<?= $welcome, "\n" ?>
	<?= $visit, "\n" ?>
</div>

<div class="hr"><hr /></div>

<div id="brd-main">
	<?= $main_title, "\n" ?>
	<?= $crumbs_top, "\n" ?>
	<?= $main_pagepost_top, "\n" ?>
	<?= $admin_menu, "\n" ?>
	<?= $admin_submenu, "\n" ?>
	<?= $main, "\n" ?>
	<?= $main_pagepost_end, "\n" ?>
	<?= $crumbs_end, "\n" ?>
</div>

<div class="hr"><hr /></div>

<div id="brd-about">
	<?= $about, "\n" ?>
</div>
<?= $debug, "\n" ?>
</div>
</div>
<?= $javascript, "\n" ?>
</body>
</html>
