<?php /* The form asking for a new password, with the errors that stopped the last request. Every variable is escaped unless it is Html. */ ?>
	<div class="main-head">
		<h2 class="hn"><span><?= $login['New password request'] ?></span></h2>
	</div>
	<div class="main-content main-frm">
		<div class="ct-box info-box">
			<p class="important"><?= $login['New password info'] ?></p>
		</div>
<?php if ($errors !== null): ?>
<?= $positions['pre_new_password_errors'] ?>
		<div class="ct-box error-box">
			<h2 class="warn hn"><?= $login['New password errors'] ?></h2>
			<ul class="error-list">
				<?= $errors, "\n" ?>
			</ul>
		</div>
<?php endif ?>
		<div id="req-msg" class="req-warn ct-box error-box">
			<p class="important"><?= $common['Required warn'] ?></p>
		</div>
		<form id="afocus" class="frm-form" method="post" accept-charset="utf-8" action="<?= $action ?>">
			<div class="hidden">
				<input type="hidden" name="form_sent" value="1" />
				<input type="hidden" name="csrf_token" value="<?= $token ?>" />
			</div>
<?= $positions['pre_group'] ?>
			<div class="frm-group group<?= $numbers['group'] ?>">
<?= $positions['pre_email'] ?>
				<div class="sf-set set<?= $numbers['email_item'] ?>">
					<div class="sf-box text required">
						<label for="fld<?= $numbers['email_field'] ?>"><span><?= $login['E-mail address'] ?></span> <small><?= $login['E-mail address help'] ?></small></label><br />
						<span class="fld-input"><input id="fld<?= $numbers['email_field'] ?>" type="email" name="req_email" value="<?= $email ?>" size="35" maxlength="80" required spellcheck="false" /></span>
					</div>
				</div>
<?= $positions['pre_group_end'] ?>
			</div>
<?= $positions['group_end'] ?>
			<div class="frm-buttons">
				<span class="submit primary"><input type="submit" name="request_pass" value="<?= $login['Submit password request'] ?>" /></span>
				<span class="cancel"><input type="submit" name="cancel" value="<?= $common['Cancel'] ?>" formnovalidate /></span>
			</div>
		</form>
	</div>
