<?php

declare(strict_types=1);

namespace PunBB\Module\LegacyBridge;

use PunBB\Module\AdminIndex\Api\BoardInformationInterface;
use PunBB\Module\AdminIndex\Event\InformationRendering;
use PunBB\Module\AdminIndex\Event\InformationRequested;
use PunBB\Module\AdminIndex\Event\PhpInfoShowing;
use PunBB\Module\Bans\Api\BanCandidatesInterface;
use PunBB\Module\Bans\Api\BansInterface;
use PunBB\Module\Bans\Event\BanAssembling;
use PunBB\Module\Bans\Event\BanChangeStep;
use PunBB\Module\Bans\Event\BanFormRendering;
use PunBB\Module\Bans\Event\BansRendering;
use PunBB\Module\Bans\Event\BansRequested;
use PunBB\Module\Bans\Event\BanTargetSelecting;
use PunBB\Module\Categories\Api\CategoriesInterface;
use PunBB\Module\Categories\Event\CategoriesRendering;
use PunBB\Module\Categories\Event\CategoriesRequested;
use PunBB\Module\Categories\Event\CategoryChangeStep;
use PunBB\Module\Categories\Event\CategoryDeletionRendering;
use PunBB\Module\Categories\Event\CategoryRendering;
use PunBB\Module\Censoring\Api\CensorsInterface;
use PunBB\Module\Censoring\Cache\CensorCacheInterface;
use PunBB\Module\Censoring\Event\CensorChangeStep;
use PunBB\Module\Censoring\Event\CensoredWordRendering;
use PunBB\Module\Censoring\Event\CensoringRendering;
use PunBB\Module\Censoring\Event\CensoringRequested;
use PunBB\Module\Database\Sql\Connection;
use PunBB\Module\Database\Schema\DbLayerSchema;
use PunBB\Module\Database\Schema\SchemaInterface;
use PunBB\Module\Install\Indexing\PostIndexInterface as InstallPostIndexInterface;
use PunBB\Module\Install\Language\InstallerLanguageInterface;
use PunBB\Module\Install\Manifest\BundledExtensionsInterface;
use PunBB\Module\LegacyBridge\Setup\LegacyBoardFiles;
use PunBB\Module\LegacyBridge\Setup\LegacyBundledExtensions;
use PunBB\Module\LegacyBridge\Setup\LegacyConfiguration;
use PunBB\Module\LegacyBridge\Setup\LegacyEnvironment;
use PunBB\Module\LegacyBridge\Setup\LegacyInstallerLanguage;
use PunBB\Module\LegacyBridge\Setup\LegacyInstallIndex;
use PunBB\Module\LegacyBridge\Setup\LegacySetupDatabase;
use PunBB\Module\LegacyBridge\Setup\LegacyUpdatePreparser;
use PunBB\Module\Setup\Config\ConfigurationInterface as SetupConfigurationInterface;
use PunBB\Module\Setup\Database\DatabaseInterface as SetupDatabaseInterface;
use PunBB\Module\Setup\Environment\EnvironmentInterface;
use PunBB\Module\Setup\Files\BoardFilesInterface;
use PunBB\Module\Update\Parsing\PreparserInterface;
use PunBB\Module\Delete\Api\DeletablePostsInterface;
use PunBB\Module\Delete\Event\DeletionPermissionChecking;
use PunBB\Module\Delete\Event\DeletionRendering;
use PunBB\Module\Delete\Event\DeletionRequested;
use PunBB\Module\Delete\Event\PostDeletionStep;
use PunBB\Module\Delete\Event\PostIdentAssembling;
use PunBB\Module\Delete\Removal\PostRemovalInterface;
use PunBB\Module\Edit\Api\EditablePostsInterface;
use PunBB\Module\Edit\Event\EditCheckboxesAssembling;
use PunBB\Module\Edit\Event\EditPermissionChecking;
use PunBB\Module\Edit\Event\EditPreviewAssembling;
use PunBB\Module\Edit\Event\EditRendering;
use PunBB\Module\Edit\Event\EditRequested;
use PunBB\Module\Edit\Event\PostEditStep;
use PunBB\Module\Edit\Indexing\EditIndexInterface;
use PunBB\Module\Extensions\Api\ExtensionsInterface;
use PunBB\Module\Extensions\Cache\ExtensionCacheInterface;
use PunBB\Module\Extensions\Event\ExtensionActionsAssembling;
use PunBB\Module\Extensions\Event\ExtensionListRendering;
use PunBB\Module\Extensions\Event\ExtensionsActionRequested;
use PunBB\Module\Extensions\Event\ExtensionsRequested;
use PunBB\Module\Extensions\Event\FlipStep;
use PunBB\Module\Extensions\Event\InstallFormRendering;
use PunBB\Module\Extensions\Event\InstallStep;
use PunBB\Module\Extensions\Event\NoticesRendering;
use PunBB\Module\Extensions\Event\UninstallFormRendering;
use PunBB\Module\Extensions\Event\UninstallStep;
use PunBB\Module\Extensions\Installation\ExtensionCodeInterface;
use PunBB\Module\Extensions\Manifest\ManifestsInterface;
use PunBB\Module\Extensions\Updates\UpdatesInterface;
use PunBB\Module\Extern\Api\SyndicationInterface;
use PunBB\Module\Extern\Authentication\BasicAuthenticationInterface;
use PunBB\Module\Extern\Event\ExternActionRequested;
use PunBB\Module\Extern\Event\ExternRequested;
use PunBB\Module\Extern\Event\FeedAssembling;
use PunBB\Module\Extern\Event\FeedRendering;
use PunBB\Module\Extern\Event\FeedRequested;
use PunBB\Module\Extern\Event\OnlineListAssembling;
use PunBB\Module\Extern\Event\StatisticsShowing;
use PunBB\Module\Forums\Api\ForumsInterface;
use PunBB\Module\Forums\Event\ForumChangeStep;
use PunBB\Module\Forums\Event\ForumDeletionRendering;
use PunBB\Module\Forums\Event\ForumFormRendering;
use PunBB\Module\Forums\Event\ForumsRendering;
use PunBB\Module\Forums\Event\ForumsRequested;
use PunBB\Module\Forums\Event\GroupPermissionRendering;
use PunBB\Module\Forums\Event\ListedForumRendering;
use PunBB\Module\Forums\Event\PermissionsComparing;
use PunBB\Module\Framework\Container\Container;
use PunBB\Module\Framework\Modules\ModuleInterface;
use PunBB\Module\Framework\Modules\Wiring;
use PunBB\Module\Groups\Api\GroupsInterface;
use PunBB\Module\Groups\Event\DefaultGroupStep;
use PunBB\Module\Groups\Event\GroupChangeStep;
use PunBB\Module\Groups\Event\GroupFormRendering;
use PunBB\Module\Groups\Event\GroupRemovalRendering;
use PunBB\Module\Groups\Event\GroupRemovalStep;
use PunBB\Module\Groups\Event\GroupRowAssembling;
use PunBB\Module\Groups\Event\GroupsRendering;
use PunBB\Module\Groups\Event\GroupsRequested;
use PunBB\Module\Help\Event\HelpRendering;
use PunBB\Module\Help\Event\HelpRequested;
use PunBB\Module\Help\Event\SmiliesListing;
use PunBB\Module\Index\Api\BoardIndexInterface;
use PunBB\Module\Index\Event\CategoryHeadAssembling;
use PunBB\Module\Index\Event\ForumRowAssembling;
use PunBB\Module\Index\Event\IndexRendering;
use PunBB\Module\Index\Event\IndexRequested;
use PunBB\Module\Index\Event\OnlineInfoAssembling;
use PunBB\Module\Index\Event\OnlineVisitorListing;
use PunBB\Module\Index\Event\StatisticsAssembling;
use PunBB\Module\LegacyBridge\Database\LegacyConnection;
use PunBB\Module\LegacyBridge\Hook\HookMap;
use PunBB\Module\LegacyBridge\Hook\MarkupHookRunner;
use PunBB\Module\LegacyBridge\Hook\PointEvaluator;
use PunBB\Module\LegacyBridge\Hook\StatementHookRunner;
use PunBB\Module\LegacyBridge\Layout\LegacyChromeFactory;
use PunBB\Module\LegacyBridge\Layout\Observer\AboutObserver;
use PunBB\Module\LegacyBridge\Layout\Observer\AdminAlertsObserver;
use PunBB\Module\LegacyBridge\Layout\Observer\BoardElementsObserver;
use PunBB\Module\LegacyBridge\Layout\Observer\DebugObserver;
use PunBB\Module\LegacyBridge\Layout\Observer\ElementsTranslation;
use PunBB\Module\LegacyBridge\Layout\Observer\HeadObserver;
use PunBB\Module\LegacyBridge\Layout\Observer\HeaderAssembledObserver;
use PunBB\Module\LegacyBridge\Layout\Observer\MainElementsObserver;
use PunBB\Module\LegacyBridge\Layout\Observer\PageRenderedObserver;
use PunBB\Module\LegacyBridge\Layout\Observer\ScriptsObserver;
use PunBB\Module\LegacyBridge\Layout\Observer\VisitElementsObserver;
use PunBB\Module\LegacyBridge\Layout\TemplateProtocol;
use PunBB\Module\LegacyBridge\Page\AdminIndex\BoardInformationPlugin;
use PunBB\Module\LegacyBridge\Page\AdminIndex\InformationRenderingObserver;
use PunBB\Module\LegacyBridge\Page\AdminIndex\InformationRequestedObserver;
use PunBB\Module\LegacyBridge\Page\AdminIndex\PhpInfoObserver;
use PunBB\Module\LegacyBridge\Page\Bans\BanAssemblingObserver;
use PunBB\Module\LegacyBridge\Page\Bans\BanCandidatesPlugin;
use PunBB\Module\LegacyBridge\Page\Bans\BanChangeObserver;
use PunBB\Module\LegacyBridge\Page\Bans\BanFormRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Bans\BansPlugin;
use PunBB\Module\LegacyBridge\Page\Bans\BansRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Bans\BansRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Bans\BanTargetObserver;
use PunBB\Module\LegacyBridge\Page\Categories\CategoriesPlugin;
use PunBB\Module\LegacyBridge\Page\Categories\CategoriesRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Categories\CategoriesRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Categories\CategoryChangeObserver;
use PunBB\Module\LegacyBridge\Page\Categories\CategoryDeletionObserver;
use PunBB\Module\LegacyBridge\Page\Categories\CategoryRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Censoring\CensorChangeObserver;
use PunBB\Module\LegacyBridge\Page\Censoring\CensoredWordObserver;
use PunBB\Module\LegacyBridge\Page\Censoring\CensoringRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Censoring\CensoringRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Censoring\CensorsPlugin;
use PunBB\Module\LegacyBridge\Page\Censoring\LegacyCensorCache;
use PunBB\Module\LegacyBridge\Page\Delete\DeletablePostsPlugin;
use PunBB\Module\LegacyBridge\Page\Delete\DeletionPermissionObserver;
use PunBB\Module\LegacyBridge\Page\Delete\DeletionRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Delete\DeletionRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Delete\LegacyPostRemoval;
use PunBB\Module\LegacyBridge\Page\Delete\PostDeletionStepObserver;
use PunBB\Module\LegacyBridge\Page\Delete\PostIdentObserver;
use PunBB\Module\LegacyBridge\Page\Edit\EditablePostsPlugin;
use PunBB\Module\LegacyBridge\Page\Edit\EditCheckboxesObserver;
use PunBB\Module\LegacyBridge\Page\Edit\EditPermissionObserver;
use PunBB\Module\LegacyBridge\Page\Edit\EditPreviewObserver;
use PunBB\Module\LegacyBridge\Page\Edit\EditRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Edit\EditRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Edit\LegacyEditIndex;
use PunBB\Module\LegacyBridge\Page\Edit\PostEditStepObserver;
use PunBB\Module\LegacyBridge\Page\Extensions\ExtensionActionsObserver;
use PunBB\Module\LegacyBridge\Page\Extensions\ExtensionListObserver;
use PunBB\Module\LegacyBridge\Page\Extensions\ExtensionRows;
use PunBB\Module\LegacyBridge\Page\Extensions\ExtensionsActionObserver;
use PunBB\Module\LegacyBridge\Page\Extensions\ExtensionsPlugin;
use PunBB\Module\LegacyBridge\Page\Extensions\ExtensionsRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Extensions\FlipStepObserver;
use PunBB\Module\LegacyBridge\Page\Extensions\InstallFormObserver;
use PunBB\Module\LegacyBridge\Page\Extensions\InstallStepObserver;
use PunBB\Module\LegacyBridge\Page\Extensions\LegacyExtensionCache;
use PunBB\Module\LegacyBridge\Page\Extensions\LegacyExtensionCode;
use PunBB\Module\LegacyBridge\Page\Extensions\LegacyManifests;
use PunBB\Module\LegacyBridge\Page\Extensions\LegacyUpdates;
use PunBB\Module\LegacyBridge\Page\Extensions\NoticesObserver;
use PunBB\Module\LegacyBridge\Page\Extensions\UninstallFormObserver;
use PunBB\Module\LegacyBridge\Page\Extensions\UninstallStepObserver;
use PunBB\Module\LegacyBridge\Page\Extern\ExternActionObserver;
use PunBB\Module\LegacyBridge\Page\Extern\ExternRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Extern\FeedAssemblingObserver;
use PunBB\Module\LegacyBridge\Page\Extern\FeedRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Extern\FeedRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Extern\LegacyBasicAuthentication;
use PunBB\Module\LegacyBridge\Page\Extern\OnlineListObserver;
use PunBB\Module\LegacyBridge\Page\Extern\StatisticsShowingObserver;
use PunBB\Module\LegacyBridge\Page\Extern\SyndicationPlugin;
use PunBB\Module\LegacyBridge\Page\Forums\ForumChangeObserver;
use PunBB\Module\LegacyBridge\Page\Forums\ForumDeletionObserver;
use PunBB\Module\LegacyBridge\Page\Forums\ForumFormObserver;
use PunBB\Module\LegacyBridge\Page\Forums\ForumsPlugin;
use PunBB\Module\LegacyBridge\Page\Forums\ForumsRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Forums\ForumsRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Forums\ForumsRows;
use PunBB\Module\LegacyBridge\Page\Forums\GroupPermissionObserver;
use PunBB\Module\LegacyBridge\Page\Forums\ListedForumObserver;
use PunBB\Module\LegacyBridge\Page\Forums\PermissionsComparingObserver;
use PunBB\Module\LegacyBridge\Page\Groups\DefaultGroupObserver;
use PunBB\Module\LegacyBridge\Page\Groups\GroupChangeObserver;
use PunBB\Module\LegacyBridge\Page\Groups\GroupFormObserver;
use PunBB\Module\LegacyBridge\Page\Groups\GroupRemovalFormObserver;
use PunBB\Module\LegacyBridge\Page\Groups\GroupRemovalObserver;
use PunBB\Module\LegacyBridge\Page\Groups\GroupRowObserver;
use PunBB\Module\LegacyBridge\Page\Groups\GroupsPlugin;
use PunBB\Module\LegacyBridge\Page\Groups\GroupsRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Groups\GroupsRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Groups\GroupsRows;
use PunBB\Module\LegacyBridge\Page\Help\HelpRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Help\HelpRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Help\SmiliesListingObserver;
use PunBB\Module\LegacyBridge\Page\Index\BoardIndexPlugin;
use PunBB\Module\LegacyBridge\Page\Index\CategoryHeadObserver;
use PunBB\Module\LegacyBridge\Page\Index\ForumRowObserver;
use PunBB\Module\LegacyBridge\Page\Index\ForumRows;
use PunBB\Module\LegacyBridge\Page\Index\IndexRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Index\IndexRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Index\OnlineInfoObserver;
use PunBB\Module\LegacyBridge\Page\Index\OnlineVisitorObserver;
use PunBB\Module\LegacyBridge\Page\Index\StatisticsObserver;
use PunBB\Module\LegacyBridge\Page\KeptRows;
use PunBB\Module\LegacyBridge\Page\Login\AccountsPlugin;
use PunBB\Module\LegacyBridge\Page\Login\LoginRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Login\LoginRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Login\LoginStepObserver;
use PunBB\Module\LegacyBridge\Page\Login\LogoutStepObserver;
use PunBB\Module\LegacyBridge\Page\Login\PasswordRequestRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Login\PasswordRequestStepObserver;
use PunBB\Module\LegacyBridge\Page\Login\PasswordResetMailingObserver;
use PunBB\Module\LegacyBridge\Page\Login\VisitsPlugin;
use PunBB\Module\LegacyBridge\Page\Message\ConfirmFormRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Message\ConfirmFormRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Message\MaintenanceShowingObserver;
use PunBB\Module\LegacyBridge\Page\Message\MessageJsonObserver;
use PunBB\Module\LegacyBridge\Page\Message\MessageRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Message\MessageShowingObserver;
use PunBB\Module\LegacyBridge\Page\Message\RedirectHeadObserver;
use PunBB\Module\LegacyBridge\Page\Message\RedirectJsonObserver;
use PunBB\Module\LegacyBridge\Page\Message\RedirectShowingObserver;
use PunBB\Module\LegacyBridge\Page\Message\ShownMessage;
use PunBB\Module\LegacyBridge\Page\Message\ShownRedirect;
use PunBB\Module\LegacyBridge\Page\Moderate\DeleteTopicsStepObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\HostLookupObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\LegacyBoardSync;
use PunBB\Module\LegacyBridge\Page\Moderate\LegacyIndexStrip;
use PunBB\Module\LegacyBridge\Page\Moderate\MergeTopicsStepObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\ModerateActionObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\ModeratedPostObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\ModeratedPostsPlugin;
use PunBB\Module\LegacyBridge\Page\Moderate\ModeratedTopicObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\ModeratedTopicsPlugin;
use PunBB\Module\LegacyBridge\Page\Moderate\ModerationFormObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\ModerationRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\ModerationRows;
use PunBB\Module\LegacyBridge\Page\Moderate\ModeratorCheckingObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\MoveTopicsStepObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\PostListObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\PostsModerationStepObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\TargetForumObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\TopicListObserver;
use PunBB\Module\LegacyBridge\Page\Moderate\TopicStateStepObserver;
use PunBB\Module\LegacyBridge\Page\PageScope;
use PunBB\Module\LegacyBridge\Page\PluggedQuery;
use PunBB\Module\LegacyBridge\Page\Misc\BoardRulesRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Misc\EmailRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Misc\EmailStepObserver;
use PunBB\Module\LegacyBridge\Page\Misc\MarkingReadObserver;
use PunBB\Module\LegacyBridge\Page\Misc\MiscActionObserver;
use PunBB\Module\LegacyBridge\Page\Misc\MiscRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Misc\ReadMarksPlugin;
use PunBB\Module\LegacyBridge\Page\Misc\RecipientsPlugin;
use PunBB\Module\LegacyBridge\Page\Misc\ReportingPlugin;
use PunBB\Module\LegacyBridge\Page\Misc\ReportRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Misc\ReportStepObserver;
use PunBB\Module\LegacyBridge\Page\Misc\SubscriptionsPlugin;
use PunBB\Module\LegacyBridge\Page\Misc\SubscriptionStepObserver;
use PunBB\Module\LegacyBridge\Page\Post\LegacyPostCreation;
use PunBB\Module\LegacyBridge\Page\Post\PostCheckboxesObserver;
use PunBB\Module\LegacyBridge\Page\Post\PostingPermissionObserver;
use PunBB\Module\LegacyBridge\Page\Post\PostingPlugin;
use PunBB\Module\LegacyBridge\Page\Post\PostingRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Post\PostingRows;
use PunBB\Module\LegacyBridge\Page\Post\PostingStepObserver;
use PunBB\Module\LegacyBridge\Page\Post\PostPreviewObserver;
use PunBB\Module\LegacyBridge\Page\Post\PostRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Post\QuoteSelectedObserver;
use PunBB\Module\LegacyBridge\Page\Post\ReviewPostObserver;
use PunBB\Module\LegacyBridge\Page\Prune\ForumOptionObserver;
use PunBB\Module\LegacyBridge\Page\Prune\LegacyTopicPruning;
use PunBB\Module\LegacyBridge\Page\Prune\PrunableTopicsPlugin;
use PunBB\Module\LegacyBridge\Page\Prune\PruneRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Prune\PruneRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Prune\PruningStepObserver;
use PunBB\Module\LegacyBridge\Page\Ranks\LegacyRankCache;
use PunBB\Module\LegacyBridge\Page\Ranks\RankChangeObserver;
use PunBB\Module\LegacyBridge\Page\Ranks\RankRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Ranks\RanksPlugin;
use PunBB\Module\LegacyBridge\Page\Ranks\RanksRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Ranks\RanksRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Reindex\IndexablePostsPlugin;
use PunBB\Module\LegacyBridge\Page\Reindex\LegacySearchIndex;
use PunBB\Module\LegacyBridge\Page\Reindex\ReindexCycleObserver;
use PunBB\Module\LegacyBridge\Page\Reindex\ReindexRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Reindex\ReindexRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Register\LegacyAccountCreation;
use PunBB\Module\LegacyBridge\Page\Register\RegistrationAlertingObserver;
use PunBB\Module\LegacyBridge\Page\Register\RegistrationRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Register\RegistrationRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Register\RegistrationsPlugin;
use PunBB\Module\LegacyBridge\Page\Register\RegistrationStepObserver;
use PunBB\Module\LegacyBridge\Page\Register\RulesRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Reports\ReportAssemblingObserver;
use PunBB\Module\LegacyBridge\Page\Reports\ReportMarkingObserver;
use PunBB\Module\LegacyBridge\Page\Reports\ReportRows;
use PunBB\Module\LegacyBridge\Page\Reports\ReportsPlugin;
use PunBB\Module\LegacyBridge\Page\Reports\ReportsRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Reports\ReportsRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Search\ForumChecklistObserver;
use PunBB\Module\LegacyBridge\Page\Search\ForumResultObserver;
use PunBB\Module\LegacyBridge\Page\Search\LegacySearchWords;
use PunBB\Module\LegacyBridge\Page\Search\NoResultsObserver;
use PunBB\Module\LegacyBridge\Page\Search\PostResultObserver;
use PunBB\Module\LegacyBridge\Page\Search\QuickSearchObserver;
use PunBB\Module\LegacyBridge\Page\Search\ResultRowStartingObserver;
use PunBB\Module\LegacyBridge\Page\Search\ResultsHeadObserver;
use PunBB\Module\LegacyBridge\Page\Search\ResultsPlugin;
use PunBB\Module\LegacyBridge\Page\Search\ResultsRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Search\SearchActionObserver;
use PunBB\Module\LegacyBridge\Page\Search\SearchCachingObserver;
use PunBB\Module\LegacyBridge\Page\Search\SearchesPlugin;
use PunBB\Module\LegacyBridge\Page\Search\SearchFormObserver;
use PunBB\Module\LegacyBridge\Page\Search\SearchRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Search\SearchRows;
use PunBB\Module\LegacyBridge\Page\Search\SearchStepObserver;
use PunBB\Module\LegacyBridge\Page\Search\TopicResultObserver;
use PunBB\Module\LegacyBridge\Page\Search\TopicResultsHeadObserver;
use PunBB\Module\LegacyBridge\Page\Userlist\MemberDirectoryPlugin;
use PunBB\Module\LegacyBridge\Page\Userlist\MemberRowObserver;
use PunBB\Module\LegacyBridge\Page\Userlist\MemberRows;
use PunBB\Module\LegacyBridge\Page\Userlist\MemberRowStartingObserver;
use PunBB\Module\LegacyBridge\Page\Userlist\MemberTableObserver;
use PunBB\Module\LegacyBridge\Page\Userlist\UserListRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Userlist\UserListRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Users\ActionFormObserver;
use PunBB\Module\LegacyBridge\Page\Users\BanUsersStepObserver;
use PunBB\Module\LegacyBridge\Page\Users\ChangeGroupStepObserver;
use PunBB\Module\LegacyBridge\Page\Users\DeleteUsersStepObserver;
use PunBB\Module\LegacyBridge\Site\LegacyUserRemoval;
use PunBB\Module\LegacyBridge\Page\Users\ModerationButtonsObserver;
use PunBB\Module\LegacyBridge\Page\Users\ResultRowObserver;
use PunBB\Module\LegacyBridge\Page\Users\ResultsEndingObserver;
use PunBB\Module\LegacyBridge\Page\Users\ResultsTableObserver;
use PunBB\Module\LegacyBridge\Page\Users\SearchSelectedObserver;
use PunBB\Module\LegacyBridge\Page\Users\SelectedAction;
use PunBB\Module\LegacyBridge\Page\Users\UsersActionObserver;
use PunBB\Module\LegacyBridge\Page\Users\UserSearchFormObserver;
use PunBB\Module\LegacyBridge\Page\Users\UsersPlugin;
use PunBB\Module\LegacyBridge\Page\Users\UsersRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Users\UsersRows;
use PunBB\Module\LegacyBridge\Page\Viewforum\EmptyForumObserver;
use PunBB\Module\LegacyBridge\Page\Viewforum\ForumTopicsPlugin;
use PunBB\Module\LegacyBridge\Page\Viewforum\ForumViewEndingObserver;
use PunBB\Module\LegacyBridge\Page\Viewforum\ForumViewRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Viewforum\ForumViewStepObserver;
use PunBB\Module\LegacyBridge\Page\Viewforum\TopicListHeadObserver;
use PunBB\Module\LegacyBridge\Page\Viewforum\TopicRowObserver;
use PunBB\Module\LegacyBridge\Page\Viewforum\TopicRows;
use PunBB\Module\LegacyBridge\Page\Viewforum\TopicsListingObserver;
use PunBB\Module\LegacyBridge\Page\Viewtopic\NewPostSeekingObserver;
use PunBB\Module\LegacyBridge\Page\Viewtopic\PostAssemblingObserver;
use PunBB\Module\LegacyBridge\Page\Viewtopic\QuickPostObserver;
use PunBB\Module\LegacyBridge\Page\Viewtopic\TopicOptionsObserver;
use PunBB\Module\LegacyBridge\Page\Viewtopic\TopicPostsPlugin;
use PunBB\Module\LegacyBridge\Page\Viewtopic\ViewedTopicRows;
use PunBB\Module\LegacyBridge\Page\Viewtopic\TopicViewEndingObserver;
use PunBB\Module\LegacyBridge\Page\Viewtopic\TopicViewRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Viewtopic\TopicViewStepObserver;
use PunBB\Module\LegacyBridge\Site\LegacyBanCache;
use PunBB\Module\LegacyBridge\Site\LegacyConfigCache;
use PunBB\Module\LegacyBridge\Site\LegacyCsrfTokens;
use PunBB\Module\LegacyBridge\Site\LegacyDeferredWork;
use PunBB\Module\LegacyBridge\Site\LegacyEmailAddresses;
use PunBB\Module\LegacyBridge\Site\LegacyFlashMessages;
use PunBB\Module\LegacyBridge\Site\LegacyFormatter;
use PunBB\Module\LegacyBridge\Site\LegacyForumContents;
use PunBB\Module\LegacyBridge\Site\LegacyLanguage;
use PunBB\Module\LegacyBridge\Site\LegacyMailer;
use PunBB\Module\LegacyBridge\Site\LegacyModeratorLists;
use PunBB\Module\LegacyBridge\Site\LegacyPasswords;
use PunBB\Module\LegacyBridge\Site\LegacyPostRules;
use PunBB\Module\LegacyBridge\Site\LegacyQuickjumpCache;
use PunBB\Module\LegacyBridge\Site\LegacyRandomKeys;
use PunBB\Module\LegacyBridge\Site\LegacySignIn;
use PunBB\Module\LegacyBridge\Site\LegacySettings;
use PunBB\Module\LegacyBridge\Site\LegacyUrls;
use PunBB\Module\LegacyBridge\Site\LegacyUsernameRules;
use PunBB\Module\LegacyBridge\Site\LegacyVisitor;
use PunBB\Module\Layout\Chrome\ChromeFactoryInterface;
use PunBB\Module\Layout\Chrome\Layout;
use PunBB\Module\Layout\Event\AboutRendering;
use PunBB\Module\Layout\Event\AdminAlertsAssembling;
use PunBB\Module\Layout\Event\BoardElementsAssembling;
use PunBB\Module\Layout\Event\DebugRendering;
use PunBB\Module\Layout\Event\HeadAssembling;
use PunBB\Module\Layout\Event\HeaderAssembled;
use PunBB\Module\Layout\Event\MainElementsAssembling;
use PunBB\Module\Layout\Event\PageRendered;
use PunBB\Module\Layout\Event\ScriptsAssembling;
use PunBB\Module\Layout\Event\VisitElementsAssembling;
use PunBB\Module\LegacyBridge\Page\Profile\ActivationMailingObserver;
use PunBB\Module\LegacyBridge\Page\Profile\AvatarDeletionStepObserver;
use PunBB\Module\LegacyBridge\Page\Profile\AvatarUploadStepObserver;
use PunBB\Module\LegacyBridge\Page\Profile\BanRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Profile\DetailsUpdateStepObserver;
use PunBB\Module\LegacyBridge\Page\Profile\EmailChangeStepObserver;
use PunBB\Module\LegacyBridge\Page\Profile\GroupMembershipStepObserver;
use PunBB\Module\LegacyBridge\Page\Profile\LegacyAvatarRemoval;
use PunBB\Module\LegacyBridge\Page\Profile\ModeratorAssignmentStepObserver;
use PunBB\Module\LegacyBridge\Page\Profile\ModeratorForumObserver;
use PunBB\Module\LegacyBridge\Page\Profile\PasswordChangeStepObserver;
use PunBB\Module\LegacyBridge\Page\Profile\ProfileActionObserver;
use PunBB\Module\LegacyBridge\Page\Profile\ProfileDetailsSelectedObserver;
use PunBB\Module\LegacyBridge\Page\Profile\ProfileFlow;
use PunBB\Module\LegacyBridge\Page\Profile\ProfileMenuObserver;
use PunBB\Module\LegacyBridge\Page\Profile\ProfileRenderingObserver;
use PunBB\Module\LegacyBridge\Page\Profile\ProfileRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Profile\ProfileSectionObserver;
use PunBB\Module\LegacyBridge\Page\Profile\ProfilesPlugin;
use PunBB\Module\LegacyBridge\Page\Profile\UserDeletionStepObserver;
use PunBB\Module\Profile\Api\ProfilesInterface;
use PunBB\Module\Profile\Avatar\AvatarRemovalInterface;
use PunBB\Module\Profile\Event\ActivationMailing;
use PunBB\Module\Profile\Event\AvatarDeletionStep;
use PunBB\Module\Profile\Event\AvatarUploadStep;
use PunBB\Module\Profile\Event\BanRequested;
use PunBB\Module\Profile\Event\DetailsUpdateStep;
use PunBB\Module\Profile\Event\EmailChangeStep;
use PunBB\Module\Profile\Event\GroupMembershipStep;
use PunBB\Module\Profile\Event\ModeratorAssignmentStep;
use PunBB\Module\Profile\Event\ModeratorForumRendering;
use PunBB\Module\Profile\Event\PasswordChangeStep;
use PunBB\Module\Profile\Event\ProfileActionRequested;
use PunBB\Module\Profile\Event\ProfileDetailsSelected;
use PunBB\Module\Profile\Event\ProfileMenuAssembling;
use PunBB\Module\Profile\Event\ProfileRendering;
use PunBB\Module\Profile\Event\ProfileRequested;
use PunBB\Module\Profile\Event\ProfileSectionRequested;
use PunBB\Module\Profile\Event\UserDeletionStep;
use PunBB\Module\LegacyBridge\Page\Settings\ConfigurationPlugin;
use PunBB\Module\LegacyBridge\Page\Settings\SettingsFormObserver;
use PunBB\Module\LegacyBridge\Page\Settings\SettingsFormStepObserver;
use PunBB\Module\LegacyBridge\Page\Settings\SettingsRequestedObserver;
use PunBB\Module\LegacyBridge\Page\Settings\SettingsSectionObserver;
use PunBB\Module\LegacyBridge\Site\LegacyPacks;
use PunBB\Module\Login\Api\AccountsInterface;
use PunBB\Module\Login\Api\VisitsInterface;
use PunBB\Module\Login\Event\LoginRendering;
use PunBB\Module\Login\Event\LoginRequested;
use PunBB\Module\Login\Event\LoginStep;
use PunBB\Module\Login\Event\LogoutStep;
use PunBB\Module\Login\Event\PasswordRequestRendering;
use PunBB\Module\Login\Event\PasswordRequestStep;
use PunBB\Module\Login\Event\PasswordResetMailing;
use PunBB\Module\Message\Event\ConfirmFormRendering;
use PunBB\Module\Message\Event\ConfirmFormRequested;
use PunBB\Module\Message\Event\MaintenanceShowing;
use PunBB\Module\Message\Event\MessageJsonSending;
use PunBB\Module\Message\Event\MessageRendering;
use PunBB\Module\Message\Event\MessageShowing;
use PunBB\Module\Message\Event\RedirectHeadAssembling;
use PunBB\Module\Message\Event\RedirectJsonSending;
use PunBB\Module\Message\Event\RedirectShowing;
use PunBB\Module\Misc\Api\ReadMarksInterface;
use PunBB\Module\Misc\Api\RecipientsInterface;
use PunBB\Module\Misc\Api\ReportingInterface;
use PunBB\Module\Misc\Api\SubscriptionsInterface;
use PunBB\Module\Misc\Event\BoardRulesRendering;
use PunBB\Module\Misc\Event\EmailRendering;
use PunBB\Module\Misc\Event\EmailStep;
use PunBB\Module\Misc\Event\MarkingReadStep;
use PunBB\Module\Misc\Event\MiscActionRequested;
use PunBB\Module\Misc\Event\MiscRequested;
use PunBB\Module\Misc\Event\ReportRendering;
use PunBB\Module\Misc\Event\ReportStep;
use PunBB\Module\Misc\Event\SubscriptionStep;
use PunBB\Module\Moderate\Api\ModeratedPostsInterface;
use PunBB\Module\Moderate\Api\ModeratedTopicsInterface;
use PunBB\Module\Moderate\Event\DeleteTopicsStep;
use PunBB\Module\Moderate\Event\HostLookupStep;
use PunBB\Module\Moderate\Event\MergeTopicsStep;
use PunBB\Module\Moderate\Event\ModerateActionRequested;
use PunBB\Module\Moderate\Event\ModeratedPostAssembling;
use PunBB\Module\Moderate\Event\ModeratedTopicAssembling;
use PunBB\Module\Moderate\Event\ModerationFormRendering;
use PunBB\Module\Moderate\Event\ModerationRequested;
use PunBB\Module\Moderate\Event\ModeratorChecking;
use PunBB\Module\Moderate\Event\MoveTopicsStep;
use PunBB\Module\Moderate\Event\PostListRendering;
use PunBB\Module\Moderate\Event\PostsModerationStep;
use PunBB\Module\Moderate\Event\TargetForumRendering;
use PunBB\Module\Moderate\Event\TopicListRendering;
use PunBB\Module\Moderate\Event\TopicStateStep;
use PunBB\Module\Moderate\Indexing\PostIndexInterface;
use PunBB\Module\Moderate\Sync\BoardSyncInterface;
use PunBB\Module\Post\Api\PostingInterface;
use PunBB\Module\Post\Creation\PostCreationInterface;
use PunBB\Module\Post\Event\PostCheckboxesAssembling;
use PunBB\Module\Post\Event\PostingPermissionChecking;
use PunBB\Module\Post\Event\PostingRequested;
use PunBB\Module\Post\Event\PostingStep;
use PunBB\Module\Post\Event\PostPreviewAssembling;
use PunBB\Module\Post\Event\PostRendering;
use PunBB\Module\Post\Event\QuoteSelected;
use PunBB\Module\Post\Event\ReviewPostAssembling;
use PunBB\Module\Prune\Api\PrunableTopicsInterface;
use PunBB\Module\Prune\Event\ForumOptionRendering;
use PunBB\Module\Prune\Event\PruneRendering;
use PunBB\Module\Prune\Event\PruneRequested;
use PunBB\Module\Prune\Event\PruningStep;
use PunBB\Module\Prune\Pruning\TopicPruningInterface;
use PunBB\Module\Ranks\Api\RanksInterface;
use PunBB\Module\Ranks\Cache\RankCacheInterface;
use PunBB\Module\Ranks\Event\RankChangeStep;
use PunBB\Module\Ranks\Event\RankRendering;
use PunBB\Module\Ranks\Event\RanksRendering;
use PunBB\Module\Ranks\Event\RanksRequested;
use PunBB\Module\Reindex\Api\IndexablePostsInterface;
use PunBB\Module\Reindex\Event\ReindexCycleStep;
use PunBB\Module\Reindex\Event\ReindexRendering;
use PunBB\Module\Reindex\Event\ReindexRequested;
use PunBB\Module\Reindex\Indexing\SearchIndexInterface;
use PunBB\Module\Register\Api\RegistrationsInterface;
use PunBB\Module\Register\Creation\AccountCreationInterface;
use PunBB\Module\Register\Event\RegistrationAlerting;
use PunBB\Module\Register\Event\RegistrationRendering;
use PunBB\Module\Register\Event\RegistrationRequested;
use PunBB\Module\Register\Event\RegistrationStep;
use PunBB\Module\Register\Event\RulesRendering;
use PunBB\Module\Reports\Api\ReportsInterface;
use PunBB\Module\Reports\Event\ReportAssembling;
use PunBB\Module\Reports\Event\ReportMarkingStep;
use PunBB\Module\Reports\Event\ReportsRendering;
use PunBB\Module\Reports\Event\ReportsRequested;
use PunBB\Module\Search\Api\ResultsInterface;
use PunBB\Module\Search\Api\SearchesInterface;
use PunBB\Module\Search\Event\ForumChecklistRendering;
use PunBB\Module\Search\Event\ForumResultAssembling;
use PunBB\Module\Search\Event\NoResultsShowing;
use PunBB\Module\Search\Event\PostResultAssembling;
use PunBB\Module\Search\Event\QuickSearchSelected;
use PunBB\Module\Search\Event\ResultRowStarting;
use PunBB\Module\Search\Event\ResultsHeadAssembling;
use PunBB\Module\Search\Event\ResultsRendering;
use PunBB\Module\Search\Event\SearchActionValidating;
use PunBB\Module\Search\Event\SearchCaching;
use PunBB\Module\Search\Event\SearchFormRendering;
use PunBB\Module\Search\Event\SearchRequested;
use PunBB\Module\Search\Event\SearchStep;
use PunBB\Module\Search\Event\TopicResultAssembling;
use PunBB\Module\Search\Event\TopicResultsHeadAssembling;
use PunBB\Module\Search\Words\SearchWordsInterface;
use PunBB\Module\Settings\Api\ConfigurationInterface;
use PunBB\Module\Settings\Event\SettingsFormRendering;
use PunBB\Module\Settings\Event\SettingsFormStep;
use PunBB\Module\Settings\Event\SettingsRequested;
use PunBB\Module\Settings\Event\SettingsSectionRequested;
use PunBB\Module\Site\Account\UsernameRulesInterface;
use PunBB\Module\Site\Cache\BanCacheInterface;
use PunBB\Module\Site\Cache\ConfigCacheInterface;
use PunBB\Module\Site\Cache\QuickjumpCacheInterface;
use PunBB\Module\Site\Config\PacksInterface;
use PunBB\Module\Site\Config\SettingsInterface;
use PunBB\Module\Site\Flash\FlashMessagesInterface;
use PunBB\Module\Site\Format\FormatterInterface;
use PunBB\Module\Site\Language\LanguageInterface;
use PunBB\Module\Site\Mail\EmailAddressesInterface;
use PunBB\Module\Site\Mail\MailerInterface;
use PunBB\Module\Site\Moderation\ModeratorListsInterface;
use PunBB\Module\Site\Posting\PostRulesInterface;
use PunBB\Module\Site\Removal\ForumContentsInterface;
use PunBB\Module\Site\Security\CsrfTokensInterface;
use PunBB\Module\Site\Security\PasswordsInterface;
use PunBB\Module\Site\Security\RandomKeysInterface;
use PunBB\Module\Site\Security\SignInInterface;
use PunBB\Module\Site\Url\UrlsInterface;
use PunBB\Module\Site\Visitor\VisitorInterface;
use PunBB\Module\Site\Work\DeferredWorkInterface;
use PunBB\Module\Userlist\Api\MemberDirectoryInterface;
use PunBB\Module\Userlist\Event\MemberRowAssembling;
use PunBB\Module\Userlist\Event\MemberRowStarting;
use PunBB\Module\Userlist\Event\MemberTableAssembling;
use PunBB\Module\Userlist\Event\UserListRendering;
use PunBB\Module\Userlist\Event\UserListRequested;
use PunBB\Module\Users\Api\UsersInterface;
use PunBB\Module\Users\Event\ActionFormRendering;
use PunBB\Module\Users\Event\BanUsersStep;
use PunBB\Module\Users\Event\ChangeGroupStep;
use PunBB\Module\Users\Event\DeleteUsersStep;
use PunBB\Module\Users\Event\ModerationButtonsAssembling;
use PunBB\Module\Users\Event\ResultRowAssembling;
use PunBB\Module\Users\Event\ResultsEnding;
use PunBB\Module\Users\Event\ResultsTableAssembling;
use PunBB\Module\Users\Event\SearchSelected;
use PunBB\Module\Users\Event\UsersActionRequested;
use PunBB\Module\Users\Event\UserSearchFormRendering;
use PunBB\Module\Users\Event\UsersRequested;
use PunBB\Module\Site\Removal\UserRemovalInterface;
use PunBB\Module\Viewforum\Api\ForumTopicsInterface;
use PunBB\Module\Viewforum\Event\EmptyForumAssembling;
use PunBB\Module\Viewforum\Event\ForumViewEnding;
use PunBB\Module\Viewforum\Event\ForumViewRequested;
use PunBB\Module\Viewforum\Event\ForumViewStep;
use PunBB\Module\Viewforum\Event\TopicListHeadAssembling;
use PunBB\Module\Viewforum\Event\TopicRowAssembling;
use PunBB\Module\Viewforum\Event\TopicsListing;
use PunBB\Module\Viewtopic\Api\TopicPostsInterface;
use PunBB\Module\Viewtopic\Event\NewPostSeeking;
use PunBB\Module\Viewtopic\Event\PostAssembling;
use PunBB\Module\Viewtopic\Event\QuickPostRendering;
use PunBB\Module\Viewtopic\Event\TopicOptionsAssembling;
use PunBB\Module\Viewtopic\Event\TopicViewEnding;
use PunBB\Module\Viewtopic\Event\TopicViewRequested;
use PunBB\Module\Viewtopic\Event\TopicViewStep;

/**
 * The v2.0 bridge to what was written for the legacy core: extension code
 * stored for eval($hook), and pages and themes built on $tpl_main. It also
 * serves the core what the legacy bootstrap holds: the connection, the
 * visitor, the settings, the language packs and the URL scheme. Nothing else
 * in the core references it, so v2.1 deletes it whole.
 */
final class Module implements ModuleInterface {
	public function name(): string {
		return 'LegacyBridge';
	}

	/** The modules whose services, contracts and events the bridge serves, plugs and observes. */
	public function dependencies(): array {
		return array('Framework', 'Layout', 'Database', 'Site', 'Message', 'Help', 'Userlist', 'AdminIndex', 'Delete', 'Index', 'Reports', 'Reindex', 'Viewforum', 'Prune', 'Extern', 'Censoring', 'Ranks', 'Bans', 'Edit', 'Viewtopic', 'Categories', 'Login', 'Register', 'Post', 'Misc', 'Extensions', 'Search', 'Forums', 'Groups', 'Users', 'Moderate', 'Settings', 'Profile', 'Setup');
	}

	/** The installer and the updater are deleted once they have run; the bridge only serves them while they are there. */
	public function loadAfter(): array {
		return array('Install', 'Update');
	}

	public function version(): string {
		return '2.0.0';
	}

	public function wire(Wiring $wiring): void {
		$wiring->service(HookMap::class, fn (): object => new HookMap());
		$wiring->service(PointEvaluator::class, fn (Container $c): object => new PointEvaluator($c->get(HookMap::class), self::storedCode(...)));
		$wiring->service(StatementHookRunner::class, fn (Container $c): object => new StatementHookRunner($c->get(PointEvaluator::class)));
		$wiring->service(MarkupHookRunner::class, fn (Container $c): object => new MarkupHookRunner($c->get(PointEvaluator::class)));

		// What the legacy bootstrap holds, served to the core
		$wiring->service(Connection::class, fn (): object => LegacyConnection::open());
		$wiring->service(VisitorInterface::class, fn (): object => new LegacyVisitor());
		$wiring->service(SettingsInterface::class, fn (): object => new LegacySettings());
		$wiring->service(LanguageInterface::class, fn (Container $c): object => new LegacyLanguage($c->get(VisitorInterface::class)));
		$wiring->service(UrlsInterface::class, fn (): object => new LegacyUrls());
		$wiring->service(FormatterInterface::class, fn (): object => new LegacyFormatter());
		$wiring->service(CsrfTokensInterface::class, fn (): object => new LegacyCsrfTokens());
		$wiring->service(FlashMessagesInterface::class, fn (): object => new LegacyFlashMessages());
		$wiring->service(EmailAddressesInterface::class, fn (): object => new LegacyEmailAddresses());
		$wiring->service(PostRulesInterface::class, fn (): object => new LegacyPostRules());
		$wiring->service(PasswordsInterface::class, fn (): object => new LegacyPasswords());
		$wiring->service(RandomKeysInterface::class, fn (): object => new LegacyRandomKeys());
		$wiring->service(SignInInterface::class, fn (): object => new LegacySignIn());
		$wiring->service(MailerInterface::class, fn (): object => new LegacyMailer());
		$wiring->service(DeferredWorkInterface::class, fn (): object => new LegacyDeferredWork());
		$wiring->service(UsernameRulesInterface::class, fn (Container $c): object => new LegacyUsernameRules($c->get(LanguageInterface::class)));
		$wiring->service(ForumContentsInterface::class, fn (): object => new LegacyForumContents());
		$wiring->service(QuickjumpCacheInterface::class, fn (): object => new LegacyQuickjumpCache());
		$wiring->service(ConfigCacheInterface::class, fn (): object => new LegacyConfigCache());
		$wiring->service(ModeratorListsInterface::class, fn (): object => new LegacyModeratorLists());
		$wiring->service(BanCacheInterface::class, fn (): object => new LegacyBanCache());
		$wiring->service(PacksInterface::class, fn (): object => new LegacyPacks());

		// The installer and the updater, which run before a usable configuration exists
		$wiring->service(SchemaInterface::class, fn (Container $c): object => new DbLayerSchema(LegacyConnection::legacy(), $c->get(Connection::class)));
		$wiring->service(EnvironmentInterface::class, fn (): object => new LegacyEnvironment());
		$wiring->service(BoardFilesInterface::class, fn (): object => new LegacyBoardFiles());
		$wiring->service(SetupDatabaseInterface::class, fn (): object => new LegacySetupDatabase());
		$wiring->service(SetupConfigurationInterface::class, fn (): object => new LegacyConfiguration());
		$wiring->service(InstallerLanguageInterface::class, fn (): object => new LegacyInstallerLanguage());
		$wiring->service(BundledExtensionsInterface::class, fn (): object => new LegacyBundledExtensions());
		$wiring->service(InstallPostIndexInterface::class, fn (): object => new LegacyInstallIndex());
		$wiring->service(PreparserInterface::class, fn (): object => new LegacyUpdatePreparser());

		// A module's page, opened as a page script included header.php
		$wiring->service(PageScope::class, fn (Container $c): object => new PageScope($c->get(PointEvaluator::class)));
		$wiring->service(PluggedQuery::class, fn (Container $c): object => new PluggedQuery($c->get(PageScope::class)));
		$wiring->service(KeptRows::class, fn (): object => new KeptRows());
		$wiring->service(ChromeFactoryInterface::class, fn (Container $c): object => new LegacyChromeFactory($c->get(TemplateProtocol::class), $c->get(PageScope::class), $c->get(Layout::class), $c->get(PointEvaluator::class)));

		// header.php and footer.php, and the header and footer points, on the layout
		$wiring->service(TemplateProtocol::class, fn (Container $c): object => new TemplateProtocol($c->get(Layout::class), $c->get(PointEvaluator::class)));
		$wiring->service(ElementsTranslation::class, fn (Container $c): object => new ElementsTranslation($c->get(PointEvaluator::class), $c->get(TemplateProtocol::class)));

		$wiring->observer(HeadAssembling::class, HeadObserver::class, fn (Container $c): object => new HeadObserver($c->get(PointEvaluator::class)));
		$wiring->observer(BoardElementsAssembling::class, BoardElementsObserver::class, fn (Container $c): object => new BoardElementsObserver($c->get(ElementsTranslation::class)));
		$wiring->observer(VisitElementsAssembling::class, VisitElementsObserver::class, fn (Container $c): object => new VisitElementsObserver($c->get(PointEvaluator::class), $c->get(TemplateProtocol::class)));
		$wiring->observer(AdminAlertsAssembling::class, AdminAlertsObserver::class, fn (Container $c): object => new AdminAlertsObserver($c->get(PointEvaluator::class), $c->get(TemplateProtocol::class)));
		$wiring->observer(MainElementsAssembling::class, MainElementsObserver::class, fn (Container $c): object => new MainElementsObserver($c->get(ElementsTranslation::class)));
		$wiring->observer(HeaderAssembled::class, HeaderAssembledObserver::class, fn (Container $c): object => new HeaderAssembledObserver($c->get(PointEvaluator::class)));
		$wiring->observer(AboutRendering::class, AboutObserver::class, fn (Container $c): object => new AboutObserver($c->get(PointEvaluator::class)));
		$wiring->observer(DebugRendering::class, DebugObserver::class, fn (Container $c): object => new DebugObserver($c->get(PointEvaluator::class)));
		$wiring->observer(ScriptsAssembling::class, ScriptsObserver::class, fn (Container $c): object => new ScriptsObserver($c->get(PointEvaluator::class)));
		$wiring->observer(PageRendered::class, PageRenderedObserver::class, fn (Container $c): object => new PageRenderedObserver($c->get(PointEvaluator::class)));

		// message()
		$wiring->service(ShownMessage::class, fn (): object => new ShownMessage());
		$wiring->observer(MessageShowing::class, MessageShowingObserver::class, fn (Container $c): object => new MessageShowingObserver($c->get(PageScope::class), $c->get(ShownMessage::class)));
		$wiring->observer(MessageJsonSending::class, MessageJsonObserver::class, fn (Container $c): object => new MessageJsonObserver($c->get(PageScope::class), $c->get(ShownMessage::class)));
		$wiring->observer(MessageRendering::class, MessageRenderingObserver::class, fn (Container $c): object => new MessageRenderingObserver($c->get(PageScope::class), $c->get(ShownMessage::class)));

		// redirect(), csrf_confirm_form() and maintenance_message()
		$wiring->service(ShownRedirect::class, fn (): object => new ShownRedirect());
		$wiring->observer(RedirectShowing::class, RedirectShowingObserver::class, fn (Container $c): object => new RedirectShowingObserver($c->get(PageScope::class), $c->get(ShownRedirect::class)));
		$wiring->observer(RedirectJsonSending::class, RedirectJsonObserver::class, fn (Container $c): object => new RedirectJsonObserver($c->get(PageScope::class), $c->get(ShownRedirect::class)));
		$wiring->observer(RedirectHeadAssembling::class, RedirectHeadObserver::class, fn (Container $c): object => new RedirectHeadObserver($c->get(PageScope::class), $c->get(ShownRedirect::class)));
		$wiring->observer(ConfirmFormRequested::class, ConfirmFormRequestedObserver::class, fn (Container $c): object => new ConfirmFormRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(ConfirmFormRendering::class, ConfirmFormRenderingObserver::class, fn (Container $c): object => new ConfirmFormRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(MaintenanceShowing::class, MaintenanceShowingObserver::class, fn (Container $c): object => new MaintenanceShowingObserver($c->get(PageScope::class)));

		// help.php
		$wiring->observer(HelpRequested::class, HelpRequestedObserver::class, fn (Container $c): object => new HelpRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(HelpRendering::class, HelpRenderingObserver::class, fn (Container $c): object => new HelpRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(SmiliesListing::class, SmiliesListingObserver::class, fn (Container $c): object => new SmiliesListingObserver($c->get(PageScope::class)));

		// userlist.php
		$wiring->service(MemberRows::class, fn (): object => new MemberRows());
		$wiring->plugin(MemberDirectoryInterface::class, MemberDirectoryPlugin::class, fn (Container $c): object => new MemberDirectoryPlugin($c->get(PluggedQuery::class), $c->get(MemberRows::class)));
		$wiring->observer(UserListRequested::class, UserListRequestedObserver::class, fn (Container $c): object => new UserListRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(UserListRendering::class, UserListRenderingObserver::class, fn (Container $c): object => new UserListRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(MemberTableAssembling::class, MemberTableObserver::class, fn (Container $c): object => new MemberTableObserver($c->get(PageScope::class)));
		$wiring->observer(MemberRowStarting::class, MemberRowStartingObserver::class, fn (Container $c): object => new MemberRowStartingObserver($c->get(PageScope::class), $c->get(MemberRows::class)));
		$wiring->observer(MemberRowAssembling::class, MemberRowObserver::class, fn (Container $c): object => new MemberRowObserver($c->get(PageScope::class)));

		// admin/index.php
		$wiring->plugin(BoardInformationInterface::class, BoardInformationPlugin::class, fn (Container $c): object => new BoardInformationPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(InformationRequested::class, InformationRequestedObserver::class, fn (Container $c): object => new InformationRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(PhpInfoShowing::class, PhpInfoObserver::class, fn (Container $c): object => new PhpInfoObserver($c->get(PageScope::class)));
		$wiring->observer(InformationRendering::class, InformationRenderingObserver::class, fn (Container $c): object => new InformationRenderingObserver($c->get(PageScope::class)));

		// delete.php
		$wiring->service(PostRemovalInterface::class, fn (): object => new LegacyPostRemoval());
		$wiring->plugin(DeletablePostsInterface::class, DeletablePostsPlugin::class, fn (Container $c): object => new DeletablePostsPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(DeletionRequested::class, DeletionRequestedObserver::class, fn (Container $c): object => new DeletionRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(DeletionPermissionChecking::class, DeletionPermissionObserver::class, fn (Container $c): object => new DeletionPermissionObserver($c->get(PageScope::class)));
		$wiring->observer(PostDeletionStep::class, PostDeletionStepObserver::class, fn (Container $c): object => new PostDeletionStepObserver($c->get(PageScope::class)));
		$wiring->observer(PostIdentAssembling::class, PostIdentObserver::class, fn (Container $c): object => new PostIdentObserver($c->get(PageScope::class)));
		$wiring->observer(DeletionRendering::class, DeletionRenderingObserver::class, fn (Container $c): object => new DeletionRenderingObserver($c->get(PageScope::class)));

		// index.php
		$wiring->service(ForumRows::class, fn (Container $c): object => new ForumRows($c->get(KeptRows::class)));
		$wiring->plugin(BoardIndexInterface::class, BoardIndexPlugin::class, fn (Container $c): object => new BoardIndexPlugin($c->get(PluggedQuery::class), $c->get(PageScope::class), $c->get(KeptRows::class)));
		$wiring->observer(IndexRequested::class, IndexRequestedObserver::class, fn (Container $c): object => new IndexRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(IndexRendering::class, IndexRenderingObserver::class, fn (Container $c): object => new IndexRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(ForumRowAssembling::class, ForumRowObserver::class, fn (Container $c): object => new ForumRowObserver($c->get(PageScope::class), $c->get(ForumRows::class)));
		$wiring->observer(CategoryHeadAssembling::class, CategoryHeadObserver::class, fn (Container $c): object => new CategoryHeadObserver($c->get(PageScope::class), $c->get(ForumRows::class)));
		$wiring->observer(StatisticsAssembling::class, StatisticsObserver::class, fn (Container $c): object => new StatisticsObserver($c->get(PageScope::class)));
		$wiring->observer(OnlineVisitorListing::class, OnlineVisitorObserver::class, fn (Container $c): object => new OnlineVisitorObserver($c->get(PageScope::class), $c->get(KeptRows::class)));
		$wiring->observer(OnlineInfoAssembling::class, OnlineInfoObserver::class, fn (Container $c): object => new OnlineInfoObserver($c->get(PageScope::class)));

		// admin/reports.php
		$wiring->service(ReportRows::class, fn (Container $c): object => new ReportRows($c->get(KeptRows::class)));
		$wiring->plugin(ReportsInterface::class, ReportsPlugin::class, fn (Container $c): object => new ReportsPlugin($c->get(PluggedQuery::class), $c->get(ReportRows::class)));
		$wiring->observer(ReportsRequested::class, ReportsRequestedObserver::class, fn (Container $c): object => new ReportsRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(ReportMarkingStep::class, ReportMarkingObserver::class, fn (Container $c): object => new ReportMarkingObserver($c->get(PageScope::class)));
		$wiring->observer(ReportsRendering::class, ReportsRenderingObserver::class, fn (Container $c): object => new ReportsRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(ReportAssembling::class, ReportAssemblingObserver::class, fn (Container $c): object => new ReportAssemblingObserver($c->get(PageScope::class), $c->get(ReportRows::class)));

		// admin/reindex.php
		$wiring->service(SearchIndexInterface::class, fn (Container $c): object => new LegacySearchIndex($c->get(PageScope::class)));
		$wiring->plugin(IndexablePostsInterface::class, IndexablePostsPlugin::class, fn (Container $c): object => new IndexablePostsPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(ReindexRequested::class, ReindexRequestedObserver::class, fn (Container $c): object => new ReindexRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(ReindexCycleStep::class, ReindexCycleObserver::class, fn (Container $c): object => new ReindexCycleObserver($c->get(PageScope::class)));
		$wiring->observer(ReindexRendering::class, ReindexRenderingObserver::class, fn (Container $c): object => new ReindexRenderingObserver($c->get(PageScope::class)));

		// viewforum.php
		$wiring->service(TopicRows::class, fn (Container $c): object => new TopicRows($c->get(KeptRows::class)));
		$wiring->plugin(ForumTopicsInterface::class, ForumTopicsPlugin::class, fn (Container $c): object => new ForumTopicsPlugin($c->get(PluggedQuery::class), $c->get(TopicRows::class)));
		$wiring->observer(ForumViewRequested::class, ForumViewRequestedObserver::class, fn (Container $c): object => new ForumViewRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(ForumViewStep::class, ForumViewStepObserver::class, fn (Container $c): object => new ForumViewStepObserver($c->get(PageScope::class)));
		$wiring->observer(TopicListHeadAssembling::class, TopicListHeadObserver::class, fn (Container $c): object => new TopicListHeadObserver($c->get(PageScope::class)));
		$wiring->observer(TopicsListing::class, TopicsListingObserver::class, fn (Container $c): object => new TopicsListingObserver($c->get(PageScope::class), $c->get(TopicRows::class)));
		$wiring->observer(TopicRowAssembling::class, TopicRowObserver::class, fn (Container $c): object => new TopicRowObserver($c->get(PageScope::class), $c->get(TopicRows::class)));
		$wiring->observer(EmptyForumAssembling::class, EmptyForumObserver::class, fn (Container $c): object => new EmptyForumObserver($c->get(PageScope::class)));
		$wiring->observer(ForumViewEnding::class, ForumViewEndingObserver::class, fn (Container $c): object => new ForumViewEndingObserver($c->get(PageScope::class)));

		// admin/prune.php
		$wiring->service(TopicPruningInterface::class, fn (): object => new LegacyTopicPruning());
		$wiring->plugin(PrunableTopicsInterface::class, PrunableTopicsPlugin::class, fn (Container $c): object => new PrunableTopicsPlugin($c->get(PluggedQuery::class), $c->get(KeptRows::class)));
		$wiring->observer(PruneRequested::class, PruneRequestedObserver::class, fn (Container $c): object => new PruneRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(PruningStep::class, PruningStepObserver::class, fn (Container $c): object => new PruningStepObserver($c->get(PageScope::class)));
		$wiring->observer(PruneRendering::class, PruneRenderingObserver::class, fn (Container $c): object => new PruneRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(ForumOptionRendering::class, ForumOptionObserver::class, fn (Container $c): object => new ForumOptionObserver($c->get(PageScope::class), $c->get(KeptRows::class)));

		// extern.php
		$wiring->service(BasicAuthenticationInterface::class, fn (): object => new LegacyBasicAuthentication());
		$wiring->plugin(SyndicationInterface::class, SyndicationPlugin::class, fn (Container $c): object => new SyndicationPlugin($c->get(PluggedQuery::class), $c->get(KeptRows::class)));
		$wiring->observer(ExternRequested::class, ExternRequestedObserver::class, fn (Container $c): object => new ExternRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(FeedRequested::class, FeedRequestedObserver::class, fn (Container $c): object => new FeedRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(FeedAssembling::class, FeedAssemblingObserver::class, fn (Container $c): object => new FeedAssemblingObserver($c->get(PageScope::class), $c->get(KeptRows::class)));
		$wiring->observer(FeedRendering::class, FeedRenderingObserver::class, fn (Container $c): object => new FeedRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(OnlineListAssembling::class, OnlineListObserver::class, fn (Container $c): object => new OnlineListObserver($c->get(PageScope::class)));
		$wiring->observer(StatisticsShowing::class, StatisticsShowingObserver::class, fn (Container $c): object => new StatisticsShowingObserver($c->get(PageScope::class)));
		$wiring->observer(ExternActionRequested::class, ExternActionObserver::class, fn (Container $c): object => new ExternActionObserver($c->get(PageScope::class)));

		// admin/censoring.php
		$wiring->service(CensorCacheInterface::class, fn (): object => new LegacyCensorCache());
		$wiring->plugin(CensorsInterface::class, CensorsPlugin::class, fn (Container $c): object => new CensorsPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(CensoringRequested::class, CensoringRequestedObserver::class, fn (Container $c): object => new CensoringRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(CensorChangeStep::class, CensorChangeObserver::class, fn (Container $c): object => new CensorChangeObserver($c->get(PageScope::class)));
		$wiring->observer(CensoringRendering::class, CensoringRenderingObserver::class, fn (Container $c): object => new CensoringRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(CensoredWordRendering::class, CensoredWordObserver::class, fn (Container $c): object => new CensoredWordObserver($c->get(PageScope::class)));

		// admin/ranks.php
		$wiring->service(RankCacheInterface::class, fn (): object => new LegacyRankCache());
		$wiring->plugin(RanksInterface::class, RanksPlugin::class, fn (Container $c): object => new RanksPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(RanksRequested::class, RanksRequestedObserver::class, fn (Container $c): object => new RanksRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(RankChangeStep::class, RankChangeObserver::class, fn (Container $c): object => new RankChangeObserver($c->get(PageScope::class)));
		$wiring->observer(RanksRendering::class, RanksRenderingObserver::class, fn (Container $c): object => new RanksRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(RankRendering::class, RankRenderingObserver::class, fn (Container $c): object => new RankRenderingObserver($c->get(PageScope::class)));

		// admin/bans.php
		$wiring->plugin(BansInterface::class, BansPlugin::class, fn (Container $c): object => new BansPlugin($c->get(PluggedQuery::class)));
		$wiring->plugin(BanCandidatesInterface::class, BanCandidatesPlugin::class, fn (Container $c): object => new BanCandidatesPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(BansRequested::class, BansRequestedObserver::class, fn (Container $c): object => new BansRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(BanTargetSelecting::class, BanTargetObserver::class, fn (Container $c): object => new BanTargetObserver($c->get(PageScope::class)));
		$wiring->observer(BanChangeStep::class, BanChangeObserver::class, fn (Container $c): object => new BanChangeObserver($c->get(PageScope::class)));
		$wiring->observer(BanFormRendering::class, BanFormRenderingObserver::class, fn (Container $c): object => new BanFormRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(BansRendering::class, BansRenderingObserver::class, fn (Container $c): object => new BansRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(BanAssembling::class, BanAssemblingObserver::class, fn (Container $c): object => new BanAssemblingObserver($c->get(PageScope::class)));

		// edit.php
		$wiring->service(EditIndexInterface::class, fn (): object => new LegacyEditIndex());
		$wiring->plugin(EditablePostsInterface::class, EditablePostsPlugin::class, fn (Container $c): object => new EditablePostsPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(EditRequested::class, EditRequestedObserver::class, fn (Container $c): object => new EditRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(EditPermissionChecking::class, EditPermissionObserver::class, fn (Container $c): object => new EditPermissionObserver($c->get(PageScope::class)));
		$wiring->observer(PostEditStep::class, PostEditStepObserver::class, fn (Container $c): object => new PostEditStepObserver($c->get(PageScope::class)));
		$wiring->observer(EditPreviewAssembling::class, EditPreviewObserver::class, fn (Container $c): object => new EditPreviewObserver($c->get(PageScope::class)));
		$wiring->observer(EditRendering::class, EditRenderingObserver::class, fn (Container $c): object => new EditRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(EditCheckboxesAssembling::class, EditCheckboxesObserver::class, fn (Container $c): object => new EditCheckboxesObserver($c->get(PageScope::class)));

		// viewtopic.php
		$wiring->service(ViewedTopicRows::class, fn (Container $c): object => new ViewedTopicRows($c->get(KeptRows::class)));
		$wiring->plugin(TopicPostsInterface::class, TopicPostsPlugin::class, fn (Container $c): object => new TopicPostsPlugin($c->get(PluggedQuery::class), $c->get(ViewedTopicRows::class)));
		$wiring->observer(TopicViewRequested::class, TopicViewRequestedObserver::class, fn (Container $c): object => new TopicViewRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(NewPostSeeking::class, NewPostSeekingObserver::class, fn (Container $c): object => new NewPostSeekingObserver($c->get(PageScope::class)));
		$wiring->observer(TopicViewStep::class, TopicViewStepObserver::class, fn (Container $c): object => new TopicViewStepObserver($c->get(PageScope::class)));
		$wiring->observer(TopicOptionsAssembling::class, TopicOptionsObserver::class, fn (Container $c): object => new TopicOptionsObserver($c->get(PageScope::class)));
		$wiring->observer(PostAssembling::class, PostAssemblingObserver::class, fn (Container $c): object => new PostAssemblingObserver($c->get(PageScope::class), $c->get(ViewedTopicRows::class)));
		$wiring->observer(TopicViewEnding::class, TopicViewEndingObserver::class, fn (Container $c): object => new TopicViewEndingObserver($c->get(PageScope::class)));
		$wiring->observer(QuickPostRendering::class, QuickPostObserver::class, fn (Container $c): object => new QuickPostObserver($c->get(PageScope::class)));

		// admin/categories.php
		$wiring->plugin(CategoriesInterface::class, CategoriesPlugin::class, fn (Container $c): object => new CategoriesPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(CategoriesRequested::class, CategoriesRequestedObserver::class, fn (Container $c): object => new CategoriesRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(CategoryChangeStep::class, CategoryChangeObserver::class, fn (Container $c): object => new CategoryChangeObserver($c->get(PageScope::class)));
		$wiring->observer(CategoriesRendering::class, CategoriesRenderingObserver::class, fn (Container $c): object => new CategoriesRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(CategoryRendering::class, CategoryRenderingObserver::class, fn (Container $c): object => new CategoryRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(CategoryDeletionRendering::class, CategoryDeletionObserver::class, fn (Container $c): object => new CategoryDeletionObserver($c->get(PageScope::class)));

		// login.php
		$wiring->plugin(AccountsInterface::class, AccountsPlugin::class, fn (Container $c): object => new AccountsPlugin($c->get(PluggedQuery::class)));
		$wiring->plugin(VisitsInterface::class, VisitsPlugin::class, fn (Container $c): object => new VisitsPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(LoginRequested::class, LoginRequestedObserver::class, fn (Container $c): object => new LoginRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(LoginStep::class, LoginStepObserver::class, fn (Container $c): object => new LoginStepObserver($c->get(PageScope::class)));
		$wiring->observer(LogoutStep::class, LogoutStepObserver::class, fn (Container $c): object => new LogoutStepObserver($c->get(PageScope::class)));
		$wiring->observer(PasswordRequestStep::class, PasswordRequestStepObserver::class, fn (Container $c): object => new PasswordRequestStepObserver($c->get(PageScope::class)));
		$wiring->observer(PasswordResetMailing::class, PasswordResetMailingObserver::class, fn (Container $c): object => new PasswordResetMailingObserver($c->get(PageScope::class)));
		$wiring->observer(LoginRendering::class, LoginRenderingObserver::class, fn (Container $c): object => new LoginRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(PasswordRequestRendering::class, PasswordRequestRenderingObserver::class, fn (Container $c): object => new PasswordRequestRenderingObserver($c->get(PageScope::class)));

		// register.php
		$wiring->service(AccountCreationInterface::class, fn (): object => new LegacyAccountCreation());
		$wiring->plugin(RegistrationsInterface::class, RegistrationsPlugin::class, fn (Container $c): object => new RegistrationsPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(RegistrationRequested::class, RegistrationRequestedObserver::class, fn (Container $c): object => new RegistrationRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(RegistrationStep::class, RegistrationStepObserver::class, fn (Container $c): object => new RegistrationStepObserver($c->get(PageScope::class)));
		$wiring->observer(RegistrationAlerting::class, RegistrationAlertingObserver::class, fn (Container $c): object => new RegistrationAlertingObserver($c->get(PageScope::class)));
		$wiring->observer(RulesRendering::class, RulesRenderingObserver::class, fn (Container $c): object => new RulesRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(RegistrationRendering::class, RegistrationRenderingObserver::class, fn (Container $c): object => new RegistrationRenderingObserver($c->get(PageScope::class)));

		// post.php
		$wiring->service(PostCreationInterface::class, fn (): object => new LegacyPostCreation());
		$wiring->service(PostingRows::class, fn (Container $c): object => new PostingRows($c->get(KeptRows::class)));
		$wiring->plugin(PostingInterface::class, PostingPlugin::class, fn (Container $c): object => new PostingPlugin($c->get(PluggedQuery::class), $c->get(PostingRows::class)));
		$wiring->observer(PostingRequested::class, PostingRequestedObserver::class, fn (Container $c): object => new PostingRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(PostingPermissionChecking::class, PostingPermissionObserver::class, fn (Container $c): object => new PostingPermissionObserver($c->get(PageScope::class)));
		$wiring->observer(PostingStep::class, PostingStepObserver::class, fn (Container $c): object => new PostingStepObserver($c->get(PageScope::class)));
		$wiring->observer(QuoteSelected::class, QuoteSelectedObserver::class, fn (Container $c): object => new QuoteSelectedObserver($c->get(PageScope::class)));
		$wiring->observer(PostRendering::class, PostRenderingObserver::class, fn (Container $c): object => new PostRenderingObserver($c->get(PageScope::class), $c->get(SettingsInterface::class)));
		$wiring->observer(PostPreviewAssembling::class, PostPreviewObserver::class, fn (Container $c): object => new PostPreviewObserver($c->get(PageScope::class)));
		$wiring->observer(PostCheckboxesAssembling::class, PostCheckboxesObserver::class, fn (Container $c): object => new PostCheckboxesObserver($c->get(PageScope::class)));
		$wiring->observer(ReviewPostAssembling::class, ReviewPostObserver::class, fn (Container $c): object => new ReviewPostObserver($c->get(PageScope::class), $c->get(PostingRows::class)));
		// misc.php
		$wiring->plugin(ReadMarksInterface::class, ReadMarksPlugin::class, fn (Container $c): object => new ReadMarksPlugin($c->get(PluggedQuery::class)));
		$wiring->plugin(SubscriptionsInterface::class, SubscriptionsPlugin::class, fn (Container $c): object => new SubscriptionsPlugin($c->get(PluggedQuery::class)));
		$wiring->plugin(RecipientsInterface::class, RecipientsPlugin::class, fn (Container $c): object => new RecipientsPlugin($c->get(PluggedQuery::class)));
		$wiring->plugin(ReportingInterface::class, ReportingPlugin::class, fn (Container $c): object => new ReportingPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(MiscRequested::class, MiscRequestedObserver::class, fn (Container $c): object => new MiscRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(BoardRulesRendering::class, BoardRulesRenderingObserver::class, fn (Container $c): object => new BoardRulesRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(MarkingReadStep::class, MarkingReadObserver::class, fn (Container $c): object => new MarkingReadObserver($c->get(PageScope::class)));
		$wiring->observer(EmailStep::class, EmailStepObserver::class, fn (Container $c): object => new EmailStepObserver($c->get(PageScope::class)));
		$wiring->observer(EmailRendering::class, EmailRenderingObserver::class, fn (Container $c): object => new EmailRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(ReportStep::class, ReportStepObserver::class, fn (Container $c): object => new ReportStepObserver($c->get(PageScope::class)));
		$wiring->observer(ReportRendering::class, ReportRenderingObserver::class, fn (Container $c): object => new ReportRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(SubscriptionStep::class, SubscriptionStepObserver::class, fn (Container $c): object => new SubscriptionStepObserver($c->get(PageScope::class)));
		$wiring->observer(MiscActionRequested::class, MiscActionObserver::class, fn (Container $c): object => new MiscActionObserver($c->get(PageScope::class)));
		// admin/extensions.php
		$wiring->service(ExtensionRows::class, fn (Container $c): object => new ExtensionRows($c->get(KeptRows::class)));
		$wiring->service(ManifestsInterface::class, fn (Container $c): object => new LegacyManifests($c->get(ExtensionRows::class)));
		$wiring->service(ExtensionCodeInterface::class, fn (Container $c): object => new LegacyExtensionCode($c->get(ExtensionRows::class)));
		$wiring->service(ExtensionCacheInterface::class, fn (): object => new LegacyExtensionCache());
		$wiring->service(UpdatesInterface::class, fn (Container $c): object => new LegacyUpdates($c->get(PageScope::class), $c->get(ExtensionRows::class)));
		$wiring->plugin(ExtensionsInterface::class, ExtensionsPlugin::class, fn (Container $c): object => new ExtensionsPlugin($c->get(PluggedQuery::class), $c->get(ExtensionRows::class)));
		$wiring->observer(ExtensionsRequested::class, ExtensionsRequestedObserver::class, fn (Container $c): object => new ExtensionsRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(InstallStep::class, InstallStepObserver::class, fn (Container $c): object => new InstallStepObserver($c->get(PageScope::class), $c->get(ExtensionRows::class)));
		$wiring->observer(UninstallStep::class, UninstallStepObserver::class, fn (Container $c): object => new UninstallStepObserver($c->get(PageScope::class), $c->get(ExtensionRows::class)));
		$wiring->observer(FlipStep::class, FlipStepObserver::class, fn (Container $c): object => new FlipStepObserver($c->get(PageScope::class)));
		$wiring->observer(ExtensionsActionRequested::class, ExtensionsActionObserver::class, fn (Container $c): object => new ExtensionsActionObserver($c->get(PageScope::class)));
		$wiring->observer(InstallFormRendering::class, InstallFormObserver::class, fn (Container $c): object => new InstallFormObserver($c->get(PageScope::class)));
		$wiring->observer(UninstallFormRendering::class, UninstallFormObserver::class, fn (Container $c): object => new UninstallFormObserver($c->get(PageScope::class)));
		$wiring->observer(NoticesRendering::class, NoticesObserver::class, fn (Container $c): object => new NoticesObserver($c->get(PageScope::class)));
		$wiring->observer(ExtensionListRendering::class, ExtensionListObserver::class, fn (Container $c): object => new ExtensionListObserver($c->get(PageScope::class)));
		$wiring->observer(ExtensionActionsAssembling::class, ExtensionActionsObserver::class, fn (Container $c): object => new ExtensionActionsObserver($c->get(PageScope::class), $c->get(ExtensionRows::class)));
		// search.php
		$wiring->service(SearchRows::class, fn (Container $c): object => new SearchRows($c->get(KeptRows::class)));
		$wiring->service(SearchWordsInterface::class, fn (): object => new LegacySearchWords());
		$wiring->plugin(SearchesInterface::class, SearchesPlugin::class, fn (Container $c): object => new SearchesPlugin($c->get(PluggedQuery::class)));
		$wiring->plugin(ResultsInterface::class, ResultsPlugin::class, fn (Container $c): object => new ResultsPlugin($c->get(PageScope::class), $c->get(SearchRows::class)));
		$wiring->observer(SearchRequested::class, SearchRequestedObserver::class, fn (Container $c): object => new SearchRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(SearchActionValidating::class, SearchActionObserver::class, fn (Container $c): object => new SearchActionObserver($c->get(PageScope::class)));
		$wiring->observer(QuickSearchSelected::class, QuickSearchObserver::class, fn (Container $c): object => new QuickSearchObserver($c->get(PageScope::class)));
		$wiring->observer(SearchCaching::class, SearchCachingObserver::class, fn (Container $c): object => new SearchCachingObserver($c->get(PageScope::class)));
		$wiring->observer(SearchStep::class, SearchStepObserver::class, fn (Container $c): object => new SearchStepObserver($c->get(PageScope::class), $c->get(SearchRows::class)));
		$wiring->observer(NoResultsShowing::class, NoResultsObserver::class, fn (Container $c): object => new NoResultsObserver($c->get(PageScope::class)));
		$wiring->observer(ResultsHeadAssembling::class, ResultsHeadObserver::class, fn (Container $c): object => new ResultsHeadObserver($c->get(PageScope::class)));
		$wiring->observer(ResultsRendering::class, ResultsRenderingObserver::class, fn (Container $c): object => new ResultsRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(TopicResultsHeadAssembling::class, TopicResultsHeadObserver::class, fn (Container $c): object => new TopicResultsHeadObserver($c->get(PageScope::class)));
		$wiring->observer(ResultRowStarting::class, ResultRowStartingObserver::class, fn (Container $c): object => new ResultRowStartingObserver($c->get(PageScope::class), $c->get(SearchRows::class)));
		$wiring->observer(PostResultAssembling::class, PostResultObserver::class, fn (Container $c): object => new PostResultObserver($c->get(PageScope::class), $c->get(SearchRows::class)));
		$wiring->observer(TopicResultAssembling::class, TopicResultObserver::class, fn (Container $c): object => new TopicResultObserver($c->get(PageScope::class), $c->get(SearchRows::class)));
		$wiring->observer(ForumResultAssembling::class, ForumResultObserver::class, fn (Container $c): object => new ForumResultObserver($c->get(PageScope::class), $c->get(SearchRows::class)));
		$wiring->observer(SearchFormRendering::class, SearchFormObserver::class, fn (Container $c): object => new SearchFormObserver($c->get(PageScope::class)));
		$wiring->observer(ForumChecklistRendering::class, ForumChecklistObserver::class, fn (Container $c): object => new ForumChecklistObserver($c->get(PageScope::class), $c->get(SearchRows::class)));
		// admin/forums.php
		$wiring->service(ForumsRows::class, fn (Container $c): object => new ForumsRows($c->get(KeptRows::class)));
		$wiring->plugin(ForumsInterface::class, ForumsPlugin::class, fn (Container $c): object => new ForumsPlugin($c->get(PluggedQuery::class), $c->get(ForumsRows::class)));
		$wiring->observer(ForumsRequested::class, ForumsRequestedObserver::class, fn (Container $c): object => new ForumsRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(ForumChangeStep::class, ForumChangeObserver::class, fn (Container $c): object => new ForumChangeObserver($c->get(PageScope::class)));
		$wiring->observer(PermissionsComparing::class, PermissionsComparingObserver::class, fn (Container $c): object => new PermissionsComparingObserver($c->get(PageScope::class), $c->get(ForumsRows::class)));
		$wiring->observer(ForumsRendering::class, ForumsRenderingObserver::class, fn (Container $c): object => new ForumsRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(ListedForumRendering::class, ListedForumObserver::class, fn (Container $c): object => new ListedForumObserver($c->get(PageScope::class), $c->get(ForumsRows::class)));
		$wiring->observer(ForumFormRendering::class, ForumFormObserver::class, fn (Container $c): object => new ForumFormObserver($c->get(PageScope::class)));
		$wiring->observer(GroupPermissionRendering::class, GroupPermissionObserver::class, fn (Container $c): object => new GroupPermissionObserver($c->get(PageScope::class), $c->get(ForumsRows::class)));
		$wiring->observer(ForumDeletionRendering::class, ForumDeletionObserver::class, fn (Container $c): object => new ForumDeletionObserver($c->get(PageScope::class)));
		// admin/groups.php
		$wiring->service(GroupsRows::class, fn (Container $c): object => new GroupsRows($c->get(KeptRows::class)));
		$wiring->plugin(GroupsInterface::class, GroupsPlugin::class, fn (Container $c): object => new GroupsPlugin($c->get(PluggedQuery::class), $c->get(GroupsRows::class)));
		$wiring->observer(GroupsRequested::class, GroupsRequestedObserver::class, fn (Container $c): object => new GroupsRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(GroupChangeStep::class, GroupChangeObserver::class, fn (Container $c): object => new GroupChangeObserver($c->get(PageScope::class)));
		$wiring->observer(DefaultGroupStep::class, DefaultGroupObserver::class, fn (Container $c): object => new DefaultGroupObserver($c->get(PageScope::class)));
		$wiring->observer(GroupRemovalStep::class, GroupRemovalObserver::class, fn (Container $c): object => new GroupRemovalObserver($c->get(PageScope::class)));
		$wiring->observer(GroupsRendering::class, GroupsRenderingObserver::class, fn (Container $c): object => new GroupsRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(GroupRowAssembling::class, GroupRowObserver::class, fn (Container $c): object => new GroupRowObserver($c->get(PageScope::class), $c->get(GroupsRows::class)));
		$wiring->observer(GroupFormRendering::class, GroupFormObserver::class, fn (Container $c): object => new GroupFormObserver($c->get(PageScope::class)));
		$wiring->observer(GroupRemovalRendering::class, GroupRemovalFormObserver::class, fn (Container $c): object => new GroupRemovalFormObserver($c->get(PageScope::class)));
		// admin/users.php
		$wiring->service(UserRemovalInterface::class, fn (): object => new LegacyUserRemoval());
		$wiring->service(UsersRows::class, fn (Container $c): object => new UsersRows($c->get(KeptRows::class)));
		$wiring->service(SelectedAction::class, fn (): object => new SelectedAction());
		$wiring->plugin(UsersInterface::class, UsersPlugin::class, fn (Container $c): object => new UsersPlugin($c->get(PluggedQuery::class), $c->get(UsersRows::class), $c->get(SelectedAction::class)));
		$wiring->observer(UsersRequested::class, UsersRequestedObserver::class, fn (Container $c): object => new UsersRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(UsersActionRequested::class, UsersActionObserver::class, fn (Container $c): object => new UsersActionObserver($c->get(PageScope::class)));
		$wiring->observer(SearchSelected::class, SearchSelectedObserver::class, fn (Container $c): object => new SearchSelectedObserver($c->get(PageScope::class)));
		$wiring->observer(ResultsTableAssembling::class, ResultsTableObserver::class, fn (Container $c): object => new ResultsTableObserver($c->get(PageScope::class)));
		$wiring->observer(ResultRowAssembling::class, ResultRowObserver::class, fn (Container $c): object => new ResultRowObserver($c->get(PageScope::class), $c->get(UsersRows::class)));
		$wiring->observer(ModerationButtonsAssembling::class, ModerationButtonsObserver::class, fn (Container $c): object => new ModerationButtonsObserver($c->get(PageScope::class)));
		$wiring->observer(ResultsEnding::class, ResultsEndingObserver::class, fn (Container $c): object => new ResultsEndingObserver($c->get(PageScope::class)));
		$wiring->observer(DeleteUsersStep::class, DeleteUsersStepObserver::class, fn (Container $c): object => new DeleteUsersStepObserver($c->get(PageScope::class), $c->get(SelectedAction::class)));
		$wiring->observer(BanUsersStep::class, BanUsersStepObserver::class, fn (Container $c): object => new BanUsersStepObserver($c->get(PageScope::class), $c->get(SelectedAction::class)));
		$wiring->observer(ChangeGroupStep::class, ChangeGroupStepObserver::class, fn (Container $c): object => new ChangeGroupStepObserver($c->get(PageScope::class)));
		$wiring->observer(ActionFormRendering::class, ActionFormObserver::class, fn (Container $c): object => new ActionFormObserver($c->get(PageScope::class)));
		$wiring->observer(UserSearchFormRendering::class, UserSearchFormObserver::class, fn (Container $c): object => new UserSearchFormObserver($c->get(PageScope::class)));
		// moderate.php
		$wiring->service(BoardSyncInterface::class, fn (): object => new LegacyBoardSync());
		$wiring->service(PostIndexInterface::class, fn (): object => new LegacyIndexStrip());
		$wiring->service(ModerationRows::class, fn (Container $c): object => new ModerationRows($c->get(KeptRows::class)));
		$wiring->plugin(ModeratedPostsInterface::class, ModeratedPostsPlugin::class, fn (Container $c): object => new ModeratedPostsPlugin($c->get(PluggedQuery::class), $c->get(ModerationRows::class)));
		$wiring->plugin(ModeratedTopicsInterface::class, ModeratedTopicsPlugin::class, fn (Container $c): object => new ModeratedTopicsPlugin($c->get(PluggedQuery::class), $c->get(ModerationRows::class)));
		$wiring->observer(ModerationRequested::class, ModerationRequestedObserver::class, fn (Container $c): object => new ModerationRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(HostLookupStep::class, HostLookupObserver::class, fn (Container $c): object => new HostLookupObserver($c->get(PageScope::class)));
		$wiring->observer(ModeratorChecking::class, ModeratorCheckingObserver::class, fn (Container $c): object => new ModeratorCheckingObserver($c->get(PageScope::class)));
		$wiring->observer(PostsModerationStep::class, PostsModerationStepObserver::class, fn (Container $c): object => new PostsModerationStepObserver($c->get(PageScope::class), $c->get(ModerationRows::class)));
		$wiring->observer(MoveTopicsStep::class, MoveTopicsStepObserver::class, fn (Container $c): object => new MoveTopicsStepObserver($c->get(PageScope::class), $c->get(ModerationRows::class)));
		$wiring->observer(MergeTopicsStep::class, MergeTopicsStepObserver::class, fn (Container $c): object => new MergeTopicsStepObserver($c->get(PageScope::class)));
		$wiring->observer(DeleteTopicsStep::class, DeleteTopicsStepObserver::class, fn (Container $c): object => new DeleteTopicsStepObserver($c->get(PageScope::class), $c->get(ModerationRows::class)));
		$wiring->observer(TopicStateStep::class, TopicStateStepObserver::class, fn (Container $c): object => new TopicStateStepObserver($c->get(PageScope::class), $c->get(ModerationRows::class)));
		$wiring->observer(ModerateActionRequested::class, ModerateActionObserver::class, fn (Container $c): object => new ModerateActionObserver($c->get(PageScope::class)));
		$wiring->observer(ModerationFormRendering::class, ModerationFormObserver::class, fn (Container $c): object => new ModerationFormObserver($c->get(PageScope::class)));
		$wiring->observer(TargetForumRendering::class, TargetForumObserver::class, fn (Container $c): object => new TargetForumObserver($c->get(PageScope::class), $c->get(ModerationRows::class)));
		$wiring->observer(PostListRendering::class, PostListObserver::class, fn (Container $c): object => new PostListObserver($c->get(PageScope::class)));
		$wiring->observer(ModeratedPostAssembling::class, ModeratedPostObserver::class, fn (Container $c): object => new ModeratedPostObserver($c->get(PageScope::class), $c->get(ModerationRows::class)));
		$wiring->observer(TopicListRendering::class, TopicListObserver::class, fn (Container $c): object => new TopicListObserver($c->get(PageScope::class)));
		$wiring->observer(ModeratedTopicAssembling::class, ModeratedTopicObserver::class, fn (Container $c): object => new ModeratedTopicObserver($c->get(PageScope::class), $c->get(ModerationRows::class)));
		// admin/settings.php
		$wiring->plugin(ConfigurationInterface::class, ConfigurationPlugin::class, fn (Container $c): object => new ConfigurationPlugin($c->get(PluggedQuery::class)));
		$wiring->observer(SettingsRequested::class, SettingsRequestedObserver::class, fn (Container $c): object => new SettingsRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(SettingsFormStep::class, SettingsFormStepObserver::class, fn (Container $c): object => new SettingsFormStepObserver($c->get(PageScope::class)));
		$wiring->observer(SettingsSectionRequested::class, SettingsSectionObserver::class, fn (Container $c): object => new SettingsSectionObserver($c->get(PageScope::class)));
		$wiring->observer(SettingsFormRendering::class, SettingsFormObserver::class, fn (Container $c): object => new SettingsFormObserver($c->get(PageScope::class)));
		// profile.php
		$wiring->service(AvatarRemovalInterface::class, fn (): object => new LegacyAvatarRemoval());
		$wiring->service(ProfileFlow::class, fn (): object => new ProfileFlow());
		$wiring->plugin(ProfilesInterface::class, ProfilesPlugin::class, fn (Container $c): object => new ProfilesPlugin($c->get(PluggedQuery::class), $c->get(KeptRows::class), $c->get(ProfileFlow::class)));
		$wiring->observer(ProfileRequested::class, ProfileRequestedObserver::class, fn (Container $c): object => new ProfileRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(ProfileActionRequested::class, ProfileActionObserver::class, fn (Container $c): object => new ProfileActionObserver($c->get(PageScope::class)));
		$wiring->observer(PasswordChangeStep::class, PasswordChangeStepObserver::class, fn (Container $c): object => new PasswordChangeStepObserver($c->get(PageScope::class)));
		$wiring->observer(EmailChangeStep::class, EmailChangeStepObserver::class, fn (Container $c): object => new EmailChangeStepObserver($c->get(PageScope::class)));
		$wiring->observer(ActivationMailing::class, ActivationMailingObserver::class, fn (Container $c): object => new ActivationMailingObserver($c->get(PageScope::class)));
		$wiring->observer(UserDeletionStep::class, UserDeletionStepObserver::class, fn (Container $c): object => new UserDeletionStepObserver($c->get(PageScope::class)));
		$wiring->observer(AvatarDeletionStep::class, AvatarDeletionStepObserver::class, fn (Container $c): object => new AvatarDeletionStepObserver($c->get(PageScope::class)));
		$wiring->observer(GroupMembershipStep::class, GroupMembershipStepObserver::class, fn (Container $c): object => new GroupMembershipStepObserver($c->get(PageScope::class)));
		$wiring->observer(ModeratorAssignmentStep::class, ModeratorAssignmentStepObserver::class, fn (Container $c): object => new ModeratorAssignmentStepObserver($c->get(PageScope::class), $c->get(ProfileFlow::class)));
		$wiring->observer(BanRequested::class, BanRequestedObserver::class, fn (Container $c): object => new BanRequestedObserver($c->get(PageScope::class)));
		$wiring->observer(DetailsUpdateStep::class, DetailsUpdateStepObserver::class, fn (Container $c): object => new DetailsUpdateStepObserver($c->get(PageScope::class), $c->get(ProfileFlow::class)));
		$wiring->observer(AvatarUploadStep::class, AvatarUploadStepObserver::class, fn (Container $c): object => new AvatarUploadStepObserver($c->get(PageScope::class)));
		$wiring->observer(ProfileMenuAssembling::class, ProfileMenuObserver::class, fn (Container $c): object => new ProfileMenuObserver($c->get(PageScope::class)));
		$wiring->observer(ProfileDetailsSelected::class, ProfileDetailsSelectedObserver::class, fn (Container $c): object => new ProfileDetailsSelectedObserver($c->get(PageScope::class)));
		$wiring->observer(ProfileRendering::class, ProfileRenderingObserver::class, fn (Container $c): object => new ProfileRenderingObserver($c->get(PageScope::class)));
		$wiring->observer(ModeratorForumRendering::class, ModeratorForumObserver::class, fn (Container $c): object => new ModeratorForumObserver($c->get(PageScope::class), $c->get(KeptRows::class)));
		$wiring->observer(ProfileSectionRequested::class, ProfileSectionObserver::class, fn (Container $c): object => new ProfileSectionObserver($c->get(PageScope::class), $c->get(FormatterInterface::class)));
	}

	/** What the hooks cache holds for a point, read through get_hook() so FORUM_DISABLE_HOOKS still holds. */
	private static function storedCode(string $point): string {
		$code = \get_hook($point);

		return is_string($code) ? $code : '';
	}
}
